using FluentMigrator;
using FluentMigrator.Builders.Create.Table;
using FluentMigrator.Builders.Alter.Table;

namespace ECommerce.Migration;

public static class Constants
{
    public const int CreatedByUserId = 1;

    public enum OrderStatuses
    {
        Pending = 1,
        Processing = 2,
        Shipped = 3,
        Delivered = 4,
        Cancelled = 5,
        Refunded = 6
    }

    public enum PaymentStatuses
    {
        Pending = 1,
        Completed = 2,
        Failed = 3,
        Refunded = 4
    }

    public enum UserRoles
    {
        Customer = 1,
        Admin = 2,
        SuperAdmin = 3
    }

    public enum CouponTypes
    {
        Percentage = 1,
        FixedAmount = 2,
        FreeShipping = 3
    }
}

/// <summary>
/// Standardized string length constants
/// </summary>
public static class StringLength
{
    public const int Two = 2;
    public const int Three = 3;
    public const int Seven = 7;
    public const int Ten = 10;
    public const int Twenty = 20;
    public const int Fifty = 50;
    public const int OneHundred = 100;
    public const int TwoHundredFiftyFive = 255;
    public const int FiveHundred = 500;
    public const int TwoThousand = 2000;
}

/// <summary>
/// PostgreSQL-specific type definitions
/// </summary>
public static class PostgresSpecificType
{
    public const string Identity = "int GENERATED BY DEFAULT AS IDENTITY";
    public const string IdentitySmall = "smallint GENERATED BY DEFAULT AS IDENTITY";
    public const string IdentityBig = "bigint GENERATED BY DEFAULT AS IDENTITY";
    public const string Jsonb = "jsonb";
    public const string Uuid = "uuid";
    public const string Timestamptz = "timestamptz";
    public const string Text = "text";
}

internal static class PostgresFunction
{
    public static readonly ServerFunction NowTimestampzUTC = new("(now() at time zone 'utc')");
    public static readonly ServerFunction GenerateRandomUuidV4 = new("gen_random_uuid()");
}

public static class FluentMigratorExtensions
{
    public static ICreateTableColumnOptionOrWithColumnSyntax AutoId(this ICreateTableWithColumnOrSchemaSyntax self)
    {
        return self.WithColumn("id").AsCustom(PostgresSpecificType.Identity).NotNullable().PrimaryKey();
    }

    internal static ICreateTableColumnOptionOrWithColumnSyntax AutoIdSmall(
        this ICreateTableWithColumnOrSchemaSyntax self)
    {
        return self.WithColumn("id").AsCustom(PostgresSpecificType.IdentitySmall).NotNullable().PrimaryKey();
    }

    internal static ICreateTableColumnOptionOrWithColumnSyntax AutoIdBig(this ICreateTableWithColumnOrSchemaSyntax self)
    {
        return self.WithColumn("id").AsCustom(PostgresSpecificType.IdentityBig).NotNullable().PrimaryKey();
    }

    internal static ICreateTableColumnOptionOrWithColumnSyntax IdUuid(this ICreateTableWithColumnOrSchemaSyntax self)
    {
        return self.WithColumn("id").AsCustom(PostgresSpecificType.Uuid).NotNullable().PrimaryKey();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Uuid(this ICreateTableColumnOptionOrWithColumnSyntax self,
        bool withDefault = true, bool isNullable = false)
    {
        if (!withDefault)
            return isNullable
                ? self.WithColumn("uuid").AsCustom(PostgresSpecificType.Uuid).Nullable().Unique()
                : self.WithColumn("uuid").AsCustom(PostgresSpecificType.Uuid).NotNullable().Unique();
        if (isNullable)
            return self.WithColumn("uuid").AsCustom(PostgresSpecificType.Uuid).Nullable()
                .WithDefaultValue(new ServerFunction($"{PostgresFunction.GenerateRandomUuidV4}")).Unique();
        return self.WithColumn("uuid").AsCustom(PostgresSpecificType.Uuid).NotNullable()
            .WithDefaultValue(new ServerFunction($"{PostgresFunction.GenerateRandomUuidV4}")).Unique();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax ObjectStatus(
        this ICreateTableWithColumnOrSchemaSyntax self)
    {
        return self.WithColumn("object_status").AsInt32().NotNullable().WithDefaultValue(1).Indexed();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax ObjectStatus(
        this ICreateTableColumnOptionOrWithColumnSyntax self)
    {
        return self.WithColumn("object_status").AsInt32().NotNullable().WithDefaultValue(1).Indexed();
    }

    public static IAlterTableColumnOptionOrAddColumnOrAlterColumnSyntax ObjectStatus(
        this IAlterTableColumnOptionOrAddColumnOrAlterColumnSyntax self)
    {
        return self.AddColumn("object_status").AsInt32().NotNullable().WithDefaultValue(1).Indexed();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax IntForeignKeyIndexed(
        this ICreateTableColumnOptionOrWithColumnSyntax self,
        string name, string foreignTable, bool isNullable, bool isPK)
    {
        ICreateTableColumnOptionOrWithColumnSyntax col = isNullable
            ? self.WithColumn(name).AsInt32().Nullable().ForeignKey(foreignTable, "id")
            : self.WithColumn(name).AsInt32().NotNullable().ForeignKey(foreignTable, "id");

        if (isPK)
            col.PrimaryKey();
        else
            col.Indexed();

        return self;
    }

    public static ICreateTableWithColumnOrSchemaSyntax IntForeignKeyIndexed(
        this ICreateTableWithColumnOrSchemaSyntax self,
        string name, string foreignTable, bool isNullable, bool isPK)
    {
        ICreateTableColumnOptionOrWithColumnSyntax col = isNullable
            ? self.WithColumn(name).AsInt32().Nullable().ForeignKey(foreignTable, "id")
            : self.WithColumn(name).AsInt32().NotNullable().ForeignKey(foreignTable, "id");

        if (isPK)
            col.PrimaryKey();
        else
            col.Indexed();

        return self;
    }

    public static IAlterTableAddColumnOrAlterColumnOrSchemaOrDescriptionSyntax IntForeignKeyIndexed(
        this IAlterTableAddColumnOrAlterColumnOrSchemaOrDescriptionSyntax self,
        string name, string foreignTable, bool isNullable, bool isPK)
    {
        IAlterTableColumnOptionOrAddColumnOrAlterColumnSyntax col = isNullable
            ? self.AddColumn(name).AsInt32().Nullable().ForeignKey(foreignTable, "id")
            : self.AddColumn(name).AsInt32().NotNullable().ForeignKey(foreignTable, "id");

        if (isPK)
            col.PrimaryKey();
        else
            col.Indexed();

        return self;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax TimestampzAndDefault(
        this ICreateTableColumnOptionOrWithColumnSyntax self, string name, bool isNullable)
    {
        if (isNullable)
            self.WithColumn(name).AsCustom(PostgresSpecificType.Timestamptz).Nullable();
        else
            self.WithColumn(name).AsCustom(PostgresSpecificType.Timestamptz).NotNullable()
                .WithDefaultValue(PostgresFunction.NowTimestampzUTC);

        return self;
    }

    public static ICreateTableWithColumnOrSchemaSyntax TimestampzAndDefault(
        this ICreateTableWithColumnOrSchemaSyntax self, string name, bool isNullable)
    {
        if (isNullable)
            self.WithColumn(name).AsCustom(PostgresSpecificType.Timestamptz).Nullable();
        else
            self.WithColumn(name).AsCustom(PostgresSpecificType.Timestamptz).NotNullable()
                .WithDefaultValue(PostgresFunction.NowTimestampzUTC);

        return self;
    }

    public static IAlterTableAddColumnOrAlterColumnSyntax TimestampzAndDefault(
        this IAlterTableAddColumnOrAlterColumnSyntax self, string name, bool isNullable)
    {
        if (isNullable)
            self.AddColumn(name).AsCustom(PostgresSpecificType.Timestamptz).Nullable();
        else
            self.AddColumn(name).AsCustom(PostgresSpecificType.Timestamptz).NotNullable()
                .WithDefaultValue(PostgresFunction.NowTimestampzUTC);

        return self;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Text(this ICreateTableColumnOptionOrWithColumnSyntax self,
        string name, bool isNullable)
    {
        if (isNullable)
            self.WithColumn(name).AsCustom(PostgresSpecificType.Text).Nullable();
        else
            self.WithColumn(name).AsCustom(PostgresSpecificType.Text).NotNullable();

        return self;
    }

    public static ICreateTableWithColumnOrSchemaSyntax Text(this ICreateTableWithColumnOrSchemaSyntax self, string name,
        bool isNullable)
    {
        if (isNullable)
            self.WithColumn(name).AsCustom(PostgresSpecificType.Text).Nullable();
        else
            self.WithColumn(name).AsCustom(PostgresSpecificType.Text).NotNullable();

        return self;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Jsonb(this ICreateTableColumnOptionOrWithColumnSyntax self,
        string name, bool isNullable)
    {
        if (isNullable)
            self.WithColumn(name).AsCustom(PostgresSpecificType.Jsonb).Nullable();
        else
            self.WithColumn(name).AsCustom(PostgresSpecificType.Jsonb).NotNullable();

        return self;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax IsActive(this ICreateTableWithColumnOrSchemaSyntax self,
        bool defaultValue = true)
    {
        return self.WithColumn("is_active").AsBoolean().NotNullable().WithDefaultValue(defaultValue);
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax IsActive(
        this ICreateTableColumnOptionOrWithColumnSyntax self, bool defaultValue = true)
    {
        return self.WithColumn("is_active").AsBoolean().NotNullable().WithDefaultValue(defaultValue);
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Bool(this ICreateTableColumnOptionOrWithColumnSyntax self,
        string name, bool? defaultValue)
    {
        if (defaultValue.HasValue)
            self.WithColumn(name).AsBoolean().WithDefaultValue(defaultValue).NotNullable();
        else
            self.WithColumn(name).AsBoolean().NotNullable();

        return self;
    }
}

internal class ServerFunction
{
    private readonly string _functionName;

    public ServerFunction(string functionName)
    {
        _functionName = functionName;
    }

    public override string ToString()
    {
        return _functionName;
    }
}

public static class FluentMigratorCompositeExtensions
{
    public static ICreateTableColumnOptionOrWithColumnSyntax MultiString(
        this ICreateTableColumnOptionOrWithColumnSyntax self,
        string neutralName, int length, bool isEnglishNullable = false, bool isArabicNullable = false)
    {
        var english = self.WithColumn($"{neutralName}_en").AsString(length);
        if (isEnglishNullable)
            english.Nullable();
        else
            english.NotNullable();

        var arabic = self.WithColumn($"{neutralName}_ar").AsString(length);
        if (isArabicNullable)
            arabic.Nullable();
        else
            arabic.NotNullable();

        return self;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax MultiText(
        this ICreateTableColumnOptionOrWithColumnSyntax self,
        string neutralName, bool isEnglishNullable = true, bool isArabicNullable = true)
    {
        self.Text($"{neutralName}_en", isEnglishNullable);
        self.Text($"{neutralName}_ar", isArabicNullable);

        return self;
    }

    public static void CreateInfo(this ICreateTableColumnOptionOrWithColumnSyntax self)
    {
        self.TimestampzAndDefault("date_created_utc", false)
            .WithColumn("created_by_user_id").AsInt32().Nullable().ForeignKey(Tables.Users, "id").Indexed();
    }

    public static void ChangeInfo(this ICreateTableColumnOptionOrWithColumnSyntax self)
    {
        self.TimestampzAndDefault("date_created_utc", false)
            .WithColumn("created_by_user_id").AsInt32().Nullable().ForeignKey(Tables.Users, "id").Indexed();

        self.TimestampzAndDefault("last_modified_utc", true)
            .WithColumn("last_modified_by_user_id").AsInt32().Nullable().ForeignKey(Tables.Users, "id").Indexed();
    }

    public static void ChangeInfo(this IAlterTableAddColumnOrAlterColumnSyntax self)
    {
        self.TimestampzAndDefault("date_created_utc", false)
            .AddColumn("created_by_user_id").AsInt32().Nullable().ForeignKey(Tables.Users, "id").Indexed();

        self.TimestampzAndDefault("last_modified_utc", true)
            .AddColumn("last_modified_by_user_id").AsInt32().Nullable().ForeignKey(Tables.Users, "id").Indexed();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax SoftDelete(
        this ICreateTableColumnOptionOrWithColumnSyntax self)
    {
        return self.WithColumn("deleted_at").AsCustom(PostgresSpecificType.Timestamptz).Nullable();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax IsFeatured(
        this ICreateTableColumnOptionOrWithColumnSyntax self, bool defaultValue = false)
    {
        return self.WithColumn("is_featured").AsBoolean().NotNullable().WithDefaultValue(defaultValue).Indexed();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Metadata(
        this ICreateTableColumnOptionOrWithColumnSyntax self, bool nullable = true)
    {
        return self.Jsonb("metadata", nullable);
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Slug(
        this ICreateTableColumnOptionOrWithColumnSyntax self, bool unique = true)
    {
        var col = self.WithColumn("slug").AsString(StringLength.OneHundred).NotNullable().Indexed();
        return unique ? col.Unique() : col;
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Price(
        this ICreateTableColumnOptionOrWithColumnSyntax self,
        string columnName = "price",
        bool nullable = false)
    {
        var col = self.WithColumn(columnName).AsDecimal(18, 2);
        return nullable ? col.Nullable() : col.NotNullable();
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Quantity(
        this ICreateTableColumnOptionOrWithColumnSyntax self,
        string columnName = "quantity")
    {
        return self.WithColumn(columnName).AsInt32().NotNullable().WithDefaultValue(0);
    }

    public static ICreateTableColumnOptionOrWithColumnSyntax Rating(
        this ICreateTableColumnOptionOrWithColumnSyntax self, bool nullable = true)
    {
        var col = self.WithColumn("rating").AsDecimal(3, 2);
        return nullable ? col.Nullable() : col.NotNullable();
    }
}
