//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.HelperClasses
{
	/// <summary>Field Creation Class for entity AddressEntity</summary>
	public partial class AddressFields
	{
		/// <summary>Creates a new AddressEntity.AddressLine1 field instance</summary>
		public static EntityField2 AddressLine1 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.AddressLine1); }}
		/// <summary>Creates a new AddressEntity.AddressLine2 field instance</summary>
		public static EntityField2 AddressLine2 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.AddressLine2); }}
		/// <summary>Creates a new AddressEntity.AddressType field instance</summary>
		public static EntityField2 AddressType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.AddressType); }}
		/// <summary>Creates a new AddressEntity.City field instance</summary>
		public static EntityField2 City { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.City); }}
		/// <summary>Creates a new AddressEntity.Country field instance</summary>
		public static EntityField2 Country { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Country); }}
		/// <summary>Creates a new AddressEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.CreatedAt); }}
		/// <summary>Creates a new AddressEntity.FullName field instance</summary>
		public static EntityField2 FullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.FullName); }}
		/// <summary>Creates a new AddressEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.Id); }}
		/// <summary>Creates a new AddressEntity.IsDefault field instance</summary>
		public static EntityField2 IsDefault { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.IsDefault); }}
		/// <summary>Creates a new AddressEntity.PhoneNumber field instance</summary>
		public static EntityField2 PhoneNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.PhoneNumber); }}
		/// <summary>Creates a new AddressEntity.PostalCode field instance</summary>
		public static EntityField2 PostalCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.PostalCode); }}
		/// <summary>Creates a new AddressEntity.State field instance</summary>
		public static EntityField2 State { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.State); }}
		/// <summary>Creates a new AddressEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new AddressEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AddressFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity CartEntity</summary>
	public partial class CartFields
	{
		/// <summary>Creates a new CartEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CartEntity.Discount field instance</summary>
		public static EntityField2 Discount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Discount); }}
		/// <summary>Creates a new CartEntity.DiscountCode field instance</summary>
		public static EntityField2 DiscountCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.DiscountCode); }}
		/// <summary>Creates a new CartEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Id); }}
		/// <summary>Creates a new CartEntity.SessionId field instance</summary>
		public static EntityField2 SessionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.SessionId); }}
		/// <summary>Creates a new CartEntity.Shipping field instance</summary>
		public static EntityField2 Shipping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Shipping); }}
		/// <summary>Creates a new CartEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Subtotal); }}
		/// <summary>Creates a new CartEntity.Tax field instance</summary>
		public static EntityField2 Tax { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Tax); }}
		/// <summary>Creates a new CartEntity.Total field instance</summary>
		public static EntityField2 Total { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.Total); }}
		/// <summary>Creates a new CartEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new CartEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity CartItemEntity</summary>
	public partial class CartItemFields
	{
		/// <summary>Creates a new CartItemEntity.CartId field instance</summary>
		public static EntityField2 CartId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.CartId); }}
		/// <summary>Creates a new CartItemEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CartItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.Id); }}
		/// <summary>Creates a new CartItemEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.Price); }}
		/// <summary>Creates a new CartItemEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.ProductId); }}
		/// <summary>Creates a new CartItemEntity.Quantity field instance</summary>
		public static EntityField2 Quantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.Quantity); }}
		/// <summary>Creates a new CartItemEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.Subtotal); }}
		/// <summary>Creates a new CartItemEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartItemFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity CartSummaryViewEntity</summary>
	public partial class CartSummaryViewFields
	{
		/// <summary>Creates a new CartSummaryViewEntity.CartId field instance</summary>
		public static EntityField2 CartId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.CartId); }}
		/// <summary>Creates a new CartSummaryViewEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CartSummaryViewEntity.Discount field instance</summary>
		public static EntityField2 Discount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.Discount); }}
		/// <summary>Creates a new CartSummaryViewEntity.DiscountCode field instance</summary>
		public static EntityField2 DiscountCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.DiscountCode); }}
		/// <summary>Creates a new CartSummaryViewEntity.HoursSinceUpdate field instance</summary>
		public static EntityField2 HoursSinceUpdate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.HoursSinceUpdate); }}
		/// <summary>Creates a new CartSummaryViewEntity.SessionId field instance</summary>
		public static EntityField2 SessionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.SessionId); }}
		/// <summary>Creates a new CartSummaryViewEntity.Shipping field instance</summary>
		public static EntityField2 Shipping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.Shipping); }}
		/// <summary>Creates a new CartSummaryViewEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.Subtotal); }}
		/// <summary>Creates a new CartSummaryViewEntity.Tax field instance</summary>
		public static EntityField2 Tax { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.Tax); }}
		/// <summary>Creates a new CartSummaryViewEntity.Total field instance</summary>
		public static EntityField2 Total { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.Total); }}
		/// <summary>Creates a new CartSummaryViewEntity.TotalItems field instance</summary>
		public static EntityField2 TotalItems { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.TotalItems); }}
		/// <summary>Creates a new CartSummaryViewEntity.TotalQuantity field instance</summary>
		public static EntityField2 TotalQuantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.TotalQuantity); }}
		/// <summary>Creates a new CartSummaryViewEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new CartSummaryViewEntity.UserEmail field instance</summary>
		public static EntityField2 UserEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.UserEmail); }}
		/// <summary>Creates a new CartSummaryViewEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CartSummaryViewFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CategoryEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Description); }}
		/// <summary>Creates a new CategoryEntity.DisplayOrder field instance</summary>
		public static EntityField2 DisplayOrder { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.DisplayOrder); }}
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.ImageUrl field instance</summary>
		public static EntityField2 ImageUrl { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.ImageUrl); }}
		/// <summary>Creates a new CategoryEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.IsActive); }}
		/// <summary>Creates a new CategoryEntity.Level field instance</summary>
		public static EntityField2 Level { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Level); }}
		/// <summary>Creates a new CategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Name); }}
		/// <summary>Creates a new CategoryEntity.ParentCategoryId field instance</summary>
		public static EntityField2 ParentCategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.ParentCategoryId); }}
		/// <summary>Creates a new CategoryEntity.Slug field instance</summary>
		public static EntityField2 Slug { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Slug); }}
		/// <summary>Creates a new CategoryEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity CategoryPerformanceViewEntity</summary>
	public partial class CategoryPerformanceViewFields
	{
		/// <summary>Creates a new CategoryPerformanceViewEntity.ActiveProducts field instance</summary>
		public static EntityField2 ActiveProducts { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.ActiveProducts); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.AverageCategoryRating field instance</summary>
		public static EntityField2 AverageCategoryRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.AverageCategoryRating); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.AvgPrice field instance</summary>
		public static EntityField2 AvgPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.AvgPrice); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.CategoryId field instance</summary>
		public static EntityField2 CategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.CategoryId); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.CategoryName field instance</summary>
		public static EntityField2 CategoryName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.CategoryName); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.CategorySlug field instance</summary>
		public static EntityField2 CategorySlug { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.CategorySlug); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.MaxPrice field instance</summary>
		public static EntityField2 MaxPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.MaxPrice); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.MinPrice field instance</summary>
		public static EntityField2 MinPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.MinPrice); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.TotalProducts field instance</summary>
		public static EntityField2 TotalProducts { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.TotalProducts); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.TotalSales field instance</summary>
		public static EntityField2 TotalSales { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.TotalSales); }}
		/// <summary>Creates a new CategoryPerformanceViewEntity.TotalStock field instance</summary>
		public static EntityField2 TotalStock { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryPerformanceViewFieldIndex.TotalStock); }}
	}

	/// <summary>Field Creation Class for entity CouponEntity</summary>
	public partial class CouponFields
	{
		/// <summary>Creates a new CouponEntity.AppliesToCategories field instance</summary>
		public static EntityField2 AppliesToCategories { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.AppliesToCategories); }}
		/// <summary>Creates a new CouponEntity.AppliesToProducts field instance</summary>
		public static EntityField2 AppliesToProducts { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.AppliesToProducts); }}
		/// <summary>Creates a new CouponEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.Code); }}
		/// <summary>Creates a new CouponEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CouponEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.Description); }}
		/// <summary>Creates a new CouponEntity.DiscountType field instance</summary>
		public static EntityField2 DiscountType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.DiscountType); }}
		/// <summary>Creates a new CouponEntity.DiscountValue field instance</summary>
		public static EntityField2 DiscountValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.DiscountValue); }}
		/// <summary>Creates a new CouponEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.Id); }}
		/// <summary>Creates a new CouponEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.IsActive); }}
		/// <summary>Creates a new CouponEntity.MaxDiscountAmount field instance</summary>
		public static EntityField2 MaxDiscountAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.MaxDiscountAmount); }}
		/// <summary>Creates a new CouponEntity.MaxUses field instance</summary>
		public static EntityField2 MaxUses { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.MaxUses); }}
		/// <summary>Creates a new CouponEntity.MaxUsesPerUser field instance</summary>
		public static EntityField2 MaxUsesPerUser { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.MaxUsesPerUser); }}
		/// <summary>Creates a new CouponEntity.MinOrderAmount field instance</summary>
		public static EntityField2 MinOrderAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.MinOrderAmount); }}
		/// <summary>Creates a new CouponEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new CouponEntity.UsedCount field instance</summary>
		public static EntityField2 UsedCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.UsedCount); }}
		/// <summary>Creates a new CouponEntity.ValidFrom field instance</summary>
		public static EntityField2 ValidFrom { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.ValidFrom); }}
		/// <summary>Creates a new CouponEntity.ValidUntil field instance</summary>
		public static EntityField2 ValidUntil { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponFieldIndex.ValidUntil); }}
	}

	/// <summary>Field Creation Class for entity CouponUsageEntity</summary>
	public partial class CouponUsageFields
	{
		/// <summary>Creates a new CouponUsageEntity.CouponId field instance</summary>
		public static EntityField2 CouponId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.CouponId); }}
		/// <summary>Creates a new CouponUsageEntity.DiscountAmount field instance</summary>
		public static EntityField2 DiscountAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.DiscountAmount); }}
		/// <summary>Creates a new CouponUsageEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.Id); }}
		/// <summary>Creates a new CouponUsageEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.OrderId); }}
		/// <summary>Creates a new CouponUsageEntity.UsedAt field instance</summary>
		public static EntityField2 UsedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.UsedAt); }}
		/// <summary>Creates a new CouponUsageEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CouponUsageFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity CustomerOrdersViewEntity</summary>
	public partial class CustomerOrdersViewFields
	{
		/// <summary>Creates a new CustomerOrdersViewEntity.AverageOrderValue field instance</summary>
		public static EntityField2 AverageOrderValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.AverageOrderValue); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.CancelledOrders field instance</summary>
		public static EntityField2 CancelledOrders { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.CancelledOrders); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.CustomerSince field instance</summary>
		public static EntityField2 CustomerSince { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.CustomerSince); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.DeliveredOrders field instance</summary>
		public static EntityField2 DeliveredOrders { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.DeliveredOrders); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.Email); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.FirstName); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.FirstOrderDate field instance</summary>
		public static EntityField2 FirstOrderDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.FirstOrderDate); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.LastName); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.LastOrderDate field instance</summary>
		public static EntityField2 LastOrderDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.LastOrderDate); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.LifetimeValue field instance</summary>
		public static EntityField2 LifetimeValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.LifetimeValue); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.TotalOrders field instance</summary>
		public static EntityField2 TotalOrders { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.TotalOrders); }}
		/// <summary>Creates a new CustomerOrdersViewEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerOrdersViewFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity OrderEntity</summary>
	public partial class OrderFields
	{
		/// <summary>Creates a new OrderEntity.BillingAddressLine1 field instance</summary>
		public static EntityField2 BillingAddressLine1 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingAddressLine1); }}
		/// <summary>Creates a new OrderEntity.BillingAddressLine2 field instance</summary>
		public static EntityField2 BillingAddressLine2 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingAddressLine2); }}
		/// <summary>Creates a new OrderEntity.BillingCity field instance</summary>
		public static EntityField2 BillingCity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingCity); }}
		/// <summary>Creates a new OrderEntity.BillingCountry field instance</summary>
		public static EntityField2 BillingCountry { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingCountry); }}
		/// <summary>Creates a new OrderEntity.BillingFullName field instance</summary>
		public static EntityField2 BillingFullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingFullName); }}
		/// <summary>Creates a new OrderEntity.BillingPhone field instance</summary>
		public static EntityField2 BillingPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingPhone); }}
		/// <summary>Creates a new OrderEntity.BillingPostalCode field instance</summary>
		public static EntityField2 BillingPostalCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingPostalCode); }}
		/// <summary>Creates a new OrderEntity.BillingState field instance</summary>
		public static EntityField2 BillingState { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.BillingState); }}
		/// <summary>Creates a new OrderEntity.CancellationReason field instance</summary>
		public static EntityField2 CancellationReason { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.CancellationReason); }}
		/// <summary>Creates a new OrderEntity.CancelledAt field instance</summary>
		public static EntityField2 CancelledAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.CancelledAt); }}
		/// <summary>Creates a new OrderEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.CreatedAt); }}
		/// <summary>Creates a new OrderEntity.Currency field instance</summary>
		public static EntityField2 Currency { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Currency); }}
		/// <summary>Creates a new OrderEntity.DeliveredAt field instance</summary>
		public static EntityField2 DeliveredAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.DeliveredAt); }}
		/// <summary>Creates a new OrderEntity.Discount field instance</summary>
		public static EntityField2 Discount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Discount); }}
		/// <summary>Creates a new OrderEntity.DiscountCode field instance</summary>
		public static EntityField2 DiscountCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.DiscountCode); }}
		/// <summary>Creates a new OrderEntity.EstimatedDeliveryDate field instance</summary>
		public static EntityField2 EstimatedDeliveryDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.EstimatedDeliveryDate); }}
		/// <summary>Creates a new OrderEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Id); }}
		/// <summary>Creates a new OrderEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Notes); }}
		/// <summary>Creates a new OrderEntity.OrderNumber field instance</summary>
		public static EntityField2 OrderNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.OrderNumber); }}
		/// <summary>Creates a new OrderEntity.PaymentMethod field instance</summary>
		public static EntityField2 PaymentMethod { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.PaymentMethod); }}
		/// <summary>Creates a new OrderEntity.PaymentStatus field instance</summary>
		public static EntityField2 PaymentStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.PaymentStatus); }}
		/// <summary>Creates a new OrderEntity.PaymentTransactionId field instance</summary>
		public static EntityField2 PaymentTransactionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.PaymentTransactionId); }}
		/// <summary>Creates a new OrderEntity.ShippingAddressLine1 field instance</summary>
		public static EntityField2 ShippingAddressLine1 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingAddressLine1); }}
		/// <summary>Creates a new OrderEntity.ShippingAddressLine2 field instance</summary>
		public static EntityField2 ShippingAddressLine2 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingAddressLine2); }}
		/// <summary>Creates a new OrderEntity.ShippingCarrier field instance</summary>
		public static EntityField2 ShippingCarrier { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingCarrier); }}
		/// <summary>Creates a new OrderEntity.ShippingCity field instance</summary>
		public static EntityField2 ShippingCity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingCity); }}
		/// <summary>Creates a new OrderEntity.ShippingCost field instance</summary>
		public static EntityField2 ShippingCost { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingCost); }}
		/// <summary>Creates a new OrderEntity.ShippingCountry field instance</summary>
		public static EntityField2 ShippingCountry { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingCountry); }}
		/// <summary>Creates a new OrderEntity.ShippingFullName field instance</summary>
		public static EntityField2 ShippingFullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingFullName); }}
		/// <summary>Creates a new OrderEntity.ShippingMethod field instance</summary>
		public static EntityField2 ShippingMethod { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingMethod); }}
		/// <summary>Creates a new OrderEntity.ShippingPhone field instance</summary>
		public static EntityField2 ShippingPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingPhone); }}
		/// <summary>Creates a new OrderEntity.ShippingPostalCode field instance</summary>
		public static EntityField2 ShippingPostalCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingPostalCode); }}
		/// <summary>Creates a new OrderEntity.ShippingState field instance</summary>
		public static EntityField2 ShippingState { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.ShippingState); }}
		/// <summary>Creates a new OrderEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Status); }}
		/// <summary>Creates a new OrderEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Subtotal); }}
		/// <summary>Creates a new OrderEntity.Tax field instance</summary>
		public static EntityField2 Tax { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Tax); }}
		/// <summary>Creates a new OrderEntity.Total field instance</summary>
		public static EntityField2 Total { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Total); }}
		/// <summary>Creates a new OrderEntity.TrackingNumber field instance</summary>
		public static EntityField2 TrackingNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.TrackingNumber); }}
		/// <summary>Creates a new OrderEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new OrderEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity OrderItemEntity</summary>
	public partial class OrderItemFields
	{
		/// <summary>Creates a new OrderItemEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.CreatedAt); }}
		/// <summary>Creates a new OrderItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.Id); }}
		/// <summary>Creates a new OrderItemEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.OrderId); }}
		/// <summary>Creates a new OrderItemEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.Price); }}
		/// <summary>Creates a new OrderItemEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.ProductId); }}
		/// <summary>Creates a new OrderItemEntity.ProductImageUrl field instance</summary>
		public static EntityField2 ProductImageUrl { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.ProductImageUrl); }}
		/// <summary>Creates a new OrderItemEntity.ProductName field instance</summary>
		public static EntityField2 ProductName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.ProductName); }}
		/// <summary>Creates a new OrderItemEntity.ProductSku field instance</summary>
		public static EntityField2 ProductSku { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.ProductSku); }}
		/// <summary>Creates a new OrderItemEntity.Quantity field instance</summary>
		public static EntityField2 Quantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.Quantity); }}
		/// <summary>Creates a new OrderItemEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderItemFieldIndex.Subtotal); }}
	}

	/// <summary>Field Creation Class for entity OrderSummaryViewEntity</summary>
	public partial class OrderSummaryViewFields
	{
		/// <summary>Creates a new OrderSummaryViewEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.CreatedAt); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Currency field instance</summary>
		public static EntityField2 Currency { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Currency); }}
		/// <summary>Creates a new OrderSummaryViewEntity.CustomerName field instance</summary>
		public static EntityField2 CustomerName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.CustomerName); }}
		/// <summary>Creates a new OrderSummaryViewEntity.DeliveredAt field instance</summary>
		public static EntityField2 DeliveredAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.DeliveredAt); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Discount field instance</summary>
		public static EntityField2 Discount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Discount); }}
		/// <summary>Creates a new OrderSummaryViewEntity.EstimatedDeliveryDate field instance</summary>
		public static EntityField2 EstimatedDeliveryDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.EstimatedDeliveryDate); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Id); }}
		/// <summary>Creates a new OrderSummaryViewEntity.OrderNumber field instance</summary>
		public static EntityField2 OrderNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.OrderNumber); }}
		/// <summary>Creates a new OrderSummaryViewEntity.PaymentMethod field instance</summary>
		public static EntityField2 PaymentMethod { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.PaymentMethod); }}
		/// <summary>Creates a new OrderSummaryViewEntity.PaymentStatus field instance</summary>
		public static EntityField2 PaymentStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.PaymentStatus); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingCarrier field instance</summary>
		public static EntityField2 ShippingCarrier { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingCarrier); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingCity field instance</summary>
		public static EntityField2 ShippingCity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingCity); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingCost field instance</summary>
		public static EntityField2 ShippingCost { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingCost); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingCountry field instance</summary>
		public static EntityField2 ShippingCountry { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingCountry); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingFullName field instance</summary>
		public static EntityField2 ShippingFullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingFullName); }}
		/// <summary>Creates a new OrderSummaryViewEntity.ShippingState field instance</summary>
		public static EntityField2 ShippingState { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.ShippingState); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Status); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Subtotal field instance</summary>
		public static EntityField2 Subtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Subtotal); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Tax field instance</summary>
		public static EntityField2 Tax { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Tax); }}
		/// <summary>Creates a new OrderSummaryViewEntity.Total field instance</summary>
		public static EntityField2 Total { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.Total); }}
		/// <summary>Creates a new OrderSummaryViewEntity.TotalItems field instance</summary>
		public static EntityField2 TotalItems { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.TotalItems); }}
		/// <summary>Creates a new OrderSummaryViewEntity.TotalQuantity field instance</summary>
		public static EntityField2 TotalQuantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.TotalQuantity); }}
		/// <summary>Creates a new OrderSummaryViewEntity.TrackingNumber field instance</summary>
		public static EntityField2 TrackingNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.TrackingNumber); }}
		/// <summary>Creates a new OrderSummaryViewEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new OrderSummaryViewEntity.UserEmail field instance</summary>
		public static EntityField2 UserEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.UserEmail); }}
		/// <summary>Creates a new OrderSummaryViewEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderSummaryViewFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity PaymentEntity</summary>
	public partial class PaymentFields
	{
		/// <summary>Creates a new PaymentEntity.Amount field instance</summary>
		public static EntityField2 Amount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.Amount); }}
		/// <summary>Creates a new PaymentEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.CreatedAt); }}
		/// <summary>Creates a new PaymentEntity.Currency field instance</summary>
		public static EntityField2 Currency { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.Currency); }}
		/// <summary>Creates a new PaymentEntity.FailureReason field instance</summary>
		public static EntityField2 FailureReason { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.FailureReason); }}
		/// <summary>Creates a new PaymentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.Id); }}
		/// <summary>Creates a new PaymentEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.OrderId); }}
		/// <summary>Creates a new PaymentEntity.PaidAt field instance</summary>
		public static EntityField2 PaidAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.PaidAt); }}
		/// <summary>Creates a new PaymentEntity.PaymentMethod field instance</summary>
		public static EntityField2 PaymentMethod { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.PaymentMethod); }}
		/// <summary>Creates a new PaymentEntity.PaymentProvider field instance</summary>
		public static EntityField2 PaymentProvider { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.PaymentProvider); }}
		/// <summary>Creates a new PaymentEntity.PaypalOrderId field instance</summary>
		public static EntityField2 PaypalOrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.PaypalOrderId); }}
		/// <summary>Creates a new PaymentEntity.RefundAmount field instance</summary>
		public static EntityField2 RefundAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.RefundAmount); }}
		/// <summary>Creates a new PaymentEntity.RefundedAt field instance</summary>
		public static EntityField2 RefundedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.RefundedAt); }}
		/// <summary>Creates a new PaymentEntity.RefundReason field instance</summary>
		public static EntityField2 RefundReason { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.RefundReason); }}
		/// <summary>Creates a new PaymentEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.Status); }}
		/// <summary>Creates a new PaymentEntity.StripePaymentIntentId field instance</summary>
		public static EntityField2 StripePaymentIntentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.StripePaymentIntentId); }}
		/// <summary>Creates a new PaymentEntity.TransactionId field instance</summary>
		public static EntityField2 TransactionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.TransactionId); }}
		/// <summary>Creates a new PaymentEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new PaymentEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity ProductEntity</summary>
	public partial class ProductFields
	{
		/// <summary>Creates a new ProductEntity.AverageRating field instance</summary>
		public static EntityField2 AverageRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.AverageRating); }}
		/// <summary>Creates a new ProductEntity.Brand field instance</summary>
		public static EntityField2 Brand { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Brand); }}
		/// <summary>Creates a new ProductEntity.CategoryId field instance</summary>
		public static EntityField2 CategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.CategoryId); }}
		/// <summary>Creates a new ProductEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ProductEntity.Currency field instance</summary>
		public static EntityField2 Currency { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Currency); }}
		/// <summary>Creates a new ProductEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Description); }}
		/// <summary>Creates a new ProductEntity.Dimensions field instance</summary>
		public static EntityField2 Dimensions { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Dimensions); }}
		/// <summary>Creates a new ProductEntity.DiscountPercentage field instance</summary>
		public static EntityField2 DiscountPercentage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.DiscountPercentage); }}
		/// <summary>Creates a new ProductEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Id); }}
		/// <summary>Creates a new ProductEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.IsActive); }}
		/// <summary>Creates a new ProductEntity.IsFeatured field instance</summary>
		public static EntityField2 IsFeatured { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.IsFeatured); }}
		/// <summary>Creates a new ProductEntity.LowStockThreshold field instance</summary>
		public static EntityField2 LowStockThreshold { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.LowStockThreshold); }}
		/// <summary>Creates a new ProductEntity.MetaDescription field instance</summary>
		public static EntityField2 MetaDescription { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.MetaDescription); }}
		/// <summary>Creates a new ProductEntity.MetaKeywords field instance</summary>
		public static EntityField2 MetaKeywords { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.MetaKeywords); }}
		/// <summary>Creates a new ProductEntity.MetaTitle field instance</summary>
		public static EntityField2 MetaTitle { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.MetaTitle); }}
		/// <summary>Creates a new ProductEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Name); }}
		/// <summary>Creates a new ProductEntity.OriginalPrice field instance</summary>
		public static EntityField2 OriginalPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.OriginalPrice); }}
		/// <summary>Creates a new ProductEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Price); }}
		/// <summary>Creates a new ProductEntity.ShortDescription field instance</summary>
		public static EntityField2 ShortDescription { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ShortDescription); }}
		/// <summary>Creates a new ProductEntity.Sku field instance</summary>
		public static EntityField2 Sku { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Sku); }}
		/// <summary>Creates a new ProductEntity.Slug field instance</summary>
		public static EntityField2 Slug { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Slug); }}
		/// <summary>Creates a new ProductEntity.StockQuantity field instance</summary>
		public static EntityField2 StockQuantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.StockQuantity); }}
		/// <summary>Creates a new ProductEntity.TotalReviews field instance</summary>
		public static EntityField2 TotalReviews { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.TotalReviews); }}
		/// <summary>Creates a new ProductEntity.TotalSales field instance</summary>
		public static EntityField2 TotalSales { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.TotalSales); }}
		/// <summary>Creates a new ProductEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new ProductEntity.Weight field instance</summary>
		public static EntityField2 Weight { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Weight); }}
	}

	/// <summary>Field Creation Class for entity ProductImageEntity</summary>
	public partial class ProductImageFields
	{
		/// <summary>Creates a new ProductImageEntity.AltText field instance</summary>
		public static EntityField2 AltText { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.AltText); }}
		/// <summary>Creates a new ProductImageEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ProductImageEntity.DisplayOrder field instance</summary>
		public static EntityField2 DisplayOrder { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.DisplayOrder); }}
		/// <summary>Creates a new ProductImageEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.Id); }}
		/// <summary>Creates a new ProductImageEntity.ImageUrl field instance</summary>
		public static EntityField2 ImageUrl { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.ImageUrl); }}
		/// <summary>Creates a new ProductImageEntity.IsPrimary field instance</summary>
		public static EntityField2 IsPrimary { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.IsPrimary); }}
		/// <summary>Creates a new ProductImageEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductImageFieldIndex.ProductId); }}
	}

	/// <summary>Field Creation Class for entity ProductInventoryViewEntity</summary>
	public partial class ProductInventoryViewFields
	{
		/// <summary>Creates a new ProductInventoryViewEntity.AverageRating field instance</summary>
		public static EntityField2 AverageRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.AverageRating); }}
		/// <summary>Creates a new ProductInventoryViewEntity.CategoryName field instance</summary>
		public static EntityField2 CategoryName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.CategoryName); }}
		/// <summary>Creates a new ProductInventoryViewEntity.CategorySlug field instance</summary>
		public static EntityField2 CategorySlug { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.CategorySlug); }}
		/// <summary>Creates a new ProductInventoryViewEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ProductInventoryViewEntity.DiscountPercentage field instance</summary>
		public static EntityField2 DiscountPercentage { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.DiscountPercentage); }}
		/// <summary>Creates a new ProductInventoryViewEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.Id); }}
		/// <summary>Creates a new ProductInventoryViewEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.IsActive); }}
		/// <summary>Creates a new ProductInventoryViewEntity.IsFeatured field instance</summary>
		public static EntityField2 IsFeatured { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.IsFeatured); }}
		/// <summary>Creates a new ProductInventoryViewEntity.LowStockThreshold field instance</summary>
		public static EntityField2 LowStockThreshold { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.LowStockThreshold); }}
		/// <summary>Creates a new ProductInventoryViewEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.Name); }}
		/// <summary>Creates a new ProductInventoryViewEntity.OriginalPrice field instance</summary>
		public static EntityField2 OriginalPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.OriginalPrice); }}
		/// <summary>Creates a new ProductInventoryViewEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.Price); }}
		/// <summary>Creates a new ProductInventoryViewEntity.Sku field instance</summary>
		public static EntityField2 Sku { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.Sku); }}
		/// <summary>Creates a new ProductInventoryViewEntity.StockQuantity field instance</summary>
		public static EntityField2 StockQuantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.StockQuantity); }}
		/// <summary>Creates a new ProductInventoryViewEntity.StockStatus field instance</summary>
		public static EntityField2 StockStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.StockStatus); }}
		/// <summary>Creates a new ProductInventoryViewEntity.TotalReviews field instance</summary>
		public static EntityField2 TotalReviews { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.TotalReviews); }}
		/// <summary>Creates a new ProductInventoryViewEntity.TotalSales field instance</summary>
		public static EntityField2 TotalSales { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.TotalSales); }}
		/// <summary>Creates a new ProductInventoryViewEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductInventoryViewFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity ProductRatingViewEntity</summary>
	public partial class ProductRatingViewFields
	{
		/// <summary>Creates a new ProductRatingViewEntity.AverageRating field instance</summary>
		public static EntityField2 AverageRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.AverageRating); }}
		/// <summary>Creates a new ProductRatingViewEntity.CalculatedAvgRating field instance</summary>
		public static EntityField2 CalculatedAvgRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.CalculatedAvgRating); }}
		/// <summary>Creates a new ProductRatingViewEntity.FiveStarCount field instance</summary>
		public static EntityField2 FiveStarCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.FiveStarCount); }}
		/// <summary>Creates a new ProductRatingViewEntity.FourStarCount field instance</summary>
		public static EntityField2 FourStarCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.FourStarCount); }}
		/// <summary>Creates a new ProductRatingViewEntity.OneStarCount field instance</summary>
		public static EntityField2 OneStarCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.OneStarCount); }}
		/// <summary>Creates a new ProductRatingViewEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.ProductId); }}
		/// <summary>Creates a new ProductRatingViewEntity.ProductName field instance</summary>
		public static EntityField2 ProductName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.ProductName); }}
		/// <summary>Creates a new ProductRatingViewEntity.ThreeStarCount field instance</summary>
		public static EntityField2 ThreeStarCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.ThreeStarCount); }}
		/// <summary>Creates a new ProductRatingViewEntity.TotalReviews field instance</summary>
		public static EntityField2 TotalReviews { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.TotalReviews); }}
		/// <summary>Creates a new ProductRatingViewEntity.TwoStarCount field instance</summary>
		public static EntityField2 TwoStarCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.TwoStarCount); }}
		/// <summary>Creates a new ProductRatingViewEntity.VerifiedPurchaseCount field instance</summary>
		public static EntityField2 VerifiedPurchaseCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductRatingViewFieldIndex.VerifiedPurchaseCount); }}
	}

	/// <summary>Field Creation Class for entity ReviewEntity</summary>
	public partial class ReviewFields
	{
		/// <summary>Creates a new ReviewEntity.Comment field instance</summary>
		public static EntityField2 Comment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Comment); }}
		/// <summary>Creates a new ReviewEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ReviewEntity.HelpfulCount field instance</summary>
		public static EntityField2 HelpfulCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.HelpfulCount); }}
		/// <summary>Creates a new ReviewEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Id); }}
		/// <summary>Creates a new ReviewEntity.IsApproved field instance</summary>
		public static EntityField2 IsApproved { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.IsApproved); }}
		/// <summary>Creates a new ReviewEntity.IsVerifiedPurchase field instance</summary>
		public static EntityField2 IsVerifiedPurchase { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.IsVerifiedPurchase); }}
		/// <summary>Creates a new ReviewEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.OrderId); }}
		/// <summary>Creates a new ReviewEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.ProductId); }}
		/// <summary>Creates a new ReviewEntity.Rating field instance</summary>
		public static EntityField2 Rating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Rating); }}
		/// <summary>Creates a new ReviewEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Title); }}
		/// <summary>Creates a new ReviewEntity.UnhelpfulCount field instance</summary>
		public static EntityField2 UnhelpfulCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UnhelpfulCount); }}
		/// <summary>Creates a new ReviewEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new ReviewEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity SalesPerformanceViewEntity</summary>
	public partial class SalesPerformanceViewFields
	{
		/// <summary>Creates a new SalesPerformanceViewEntity.AverageOrderValue field instance</summary>
		public static EntityField2 AverageOrderValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.AverageOrderValue); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.OrdersCount field instance</summary>
		public static EntityField2 OrdersCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.OrdersCount); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.SaleDate field instance</summary>
		public static EntityField2 SaleDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.SaleDate); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalDiscounts field instance</summary>
		public static EntityField2 TotalDiscounts { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalDiscounts); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalItemsSold field instance</summary>
		public static EntityField2 TotalItemsSold { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalItemsSold); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalRevenue field instance</summary>
		public static EntityField2 TotalRevenue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalRevenue); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalShipping field instance</summary>
		public static EntityField2 TotalShipping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalShipping); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalSubtotal field instance</summary>
		public static EntityField2 TotalSubtotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalSubtotal); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.TotalTax field instance</summary>
		public static EntityField2 TotalTax { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.TotalTax); }}
		/// <summary>Creates a new SalesPerformanceViewEntity.UniqueCustomers field instance</summary>
		public static EntityField2 UniqueCustomers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SalesPerformanceViewFieldIndex.UniqueCustomers); }}
	}

	/// <summary>Field Creation Class for entity SavedPaymentMethodEntity</summary>
	public partial class SavedPaymentMethodFields
	{
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingAddressLine1 field instance</summary>
		public static EntityField2 BillingAddressLine1 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingAddressLine1); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingCity field instance</summary>
		public static EntityField2 BillingCity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingCity); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingCountry field instance</summary>
		public static EntityField2 BillingCountry { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingCountry); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingName field instance</summary>
		public static EntityField2 BillingName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingName); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingPostalCode field instance</summary>
		public static EntityField2 BillingPostalCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingPostalCode); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.BillingState field instance</summary>
		public static EntityField2 BillingState { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.BillingState); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.CardBrand field instance</summary>
		public static EntityField2 CardBrand { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.CardBrand); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.CardExpMonth field instance</summary>
		public static EntityField2 CardExpMonth { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.CardExpMonth); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.CardExpYear field instance</summary>
		public static EntityField2 CardExpYear { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.CardExpYear); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.CardLastFour field instance</summary>
		public static EntityField2 CardLastFour { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.CardLastFour); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.CreatedAt); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.Id); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.IsDefault field instance</summary>
		public static EntityField2 IsDefault { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.IsDefault); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.PaymentMethodType field instance</summary>
		public static EntityField2 PaymentMethodType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.PaymentMethodType); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.PaymentProvider field instance</summary>
		public static EntityField2 PaymentProvider { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.PaymentProvider); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.StripePaymentMethodId field instance</summary>
		public static EntityField2 StripePaymentMethodId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.StripePaymentMethodId); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new SavedPaymentMethodEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SavedPaymentMethodFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.CreatedAt); }}
		/// <summary>Creates a new UserEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Email); }}
		/// <summary>Creates a new UserEntity.EmailVerificationToken field instance</summary>
		public static EntityField2 EmailVerificationToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.EmailVerificationToken); }}
		/// <summary>Creates a new UserEntity.FailedLoginAttempts field instance</summary>
		public static EntityField2 FailedLoginAttempts { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.FailedLoginAttempts); }}
		/// <summary>Creates a new UserEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.FirstName); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.IsActive); }}
		/// <summary>Creates a new UserEntity.IsEmailVerified field instance</summary>
		public static EntityField2 IsEmailVerified { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.IsEmailVerified); }}
		/// <summary>Creates a new UserEntity.LastLoginAt field instance</summary>
		public static EntityField2 LastLoginAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastLoginAt); }}
		/// <summary>Creates a new UserEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastName); }}
		/// <summary>Creates a new UserEntity.LockoutEnd field instance</summary>
		public static EntityField2 LockoutEnd { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LockoutEnd); }}
		/// <summary>Creates a new UserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new UserEntity.PasswordResetExpires field instance</summary>
		public static EntityField2 PasswordResetExpires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordResetExpires); }}
		/// <summary>Creates a new UserEntity.PasswordResetToken field instance</summary>
		public static EntityField2 PasswordResetToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordResetToken); }}
		/// <summary>Creates a new UserEntity.PhoneNumber field instance</summary>
		public static EntityField2 PhoneNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PhoneNumber); }}
		/// <summary>Creates a new UserEntity.Role field instance</summary>
		public static EntityField2 Role { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Role); }}
		/// <summary>Creates a new UserEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity WishlistEntity</summary>
	public partial class WishlistFields
	{
		/// <summary>Creates a new WishlistEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.CreatedAt); }}
		/// <summary>Creates a new WishlistEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.Id); }}
		/// <summary>Creates a new WishlistEntity.IsDefault field instance</summary>
		public static EntityField2 IsDefault { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.IsDefault); }}
		/// <summary>Creates a new WishlistEntity.IsPublic field instance</summary>
		public static EntityField2 IsPublic { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.IsPublic); }}
		/// <summary>Creates a new WishlistEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.Name); }}
		/// <summary>Creates a new WishlistEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new WishlistEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity WishlistItemEntity</summary>
	public partial class WishlistItemFields
	{
		/// <summary>Creates a new WishlistItemEntity.AddedAt field instance</summary>
		public static EntityField2 AddedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistItemFieldIndex.AddedAt); }}
		/// <summary>Creates a new WishlistItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistItemFieldIndex.Id); }}
		/// <summary>Creates a new WishlistItemEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistItemFieldIndex.Notes); }}
		/// <summary>Creates a new WishlistItemEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistItemFieldIndex.ProductId); }}
		/// <summary>Creates a new WishlistItemEntity.WishlistId field instance</summary>
		public static EntityField2 WishlistId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(WishlistItemFieldIndex.WishlistId); }}
	}
	

}