//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitAddressEntityInfo();
			InitCartEntityInfo();
			InitCartItemEntityInfo();
			InitCartSummaryViewEntityInfo();
			InitCategoryEntityInfo();
			InitCategoryPerformanceViewEntityInfo();
			InitCouponEntityInfo();
			InitCouponUsageEntityInfo();
			InitCustomerOrdersViewEntityInfo();
			InitOrderEntityInfo();
			InitOrderItemEntityInfo();
			InitOrderSummaryViewEntityInfo();
			InitPaymentEntityInfo();
			InitProductEntityInfo();
			InitProductImageEntityInfo();
			InitProductInventoryViewEntityInfo();
			InitProductRatingViewEntityInfo();
			InitReviewEntityInfo();
			InitSalesPerformanceViewEntityInfo();
			InitSavedPaymentMethodEntityInfo();
			InitUserEntityInfo();
			InitWishlistEntityInfo();
			InitWishlistItemEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits AddressEntity's info objects</summary>
		private void InitAddressEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(AddressFieldIndex), "AddressEntity");
			this.AddElementFieldInfo("AddressEntity", "AddressLine1", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.AddressLine1, 255, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "AddressLine2", typeof(System.String), false, false, false, true,  (int)AddressFieldIndex.AddressLine2, 255, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "AddressType", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.AddressType, 20, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "City", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.City, 100, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "Country", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.Country, 100, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)AddressFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "FullName", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.FullName, 200, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)AddressFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "IsDefault", typeof(System.Boolean), false, false, false, false,  (int)AddressFieldIndex.IsDefault, 0, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "PhoneNumber", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.PhoneNumber, 20, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "PostalCode", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.PostalCode, 20, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "State", typeof(System.String), false, false, false, false,  (int)AddressFieldIndex.State, 100, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)AddressFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("AddressEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)AddressFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits CartEntity's info objects</summary>
		private void InitCartEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CartFieldIndex), "CartEntity");
			this.AddElementFieldInfo("CartEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CartEntity", "Discount", typeof(System.Decimal), false, false, false, false,  (int)CartFieldIndex.Discount, 0, 2, 10);
			this.AddElementFieldInfo("CartEntity", "DiscountCode", typeof(System.String), false, false, false, true,  (int)CartFieldIndex.DiscountCode, 50, 0, 0);
			this.AddElementFieldInfo("CartEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CartFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CartEntity", "SessionId", typeof(System.String), false, false, false, true,  (int)CartFieldIndex.SessionId, 100, 0, 0);
			this.AddElementFieldInfo("CartEntity", "Shipping", typeof(System.Decimal), false, false, false, false,  (int)CartFieldIndex.Shipping, 0, 2, 10);
			this.AddElementFieldInfo("CartEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)CartFieldIndex.Subtotal, 0, 2, 10);
			this.AddElementFieldInfo("CartEntity", "Tax", typeof(System.Decimal), false, false, false, false,  (int)CartFieldIndex.Tax, 0, 2, 10);
			this.AddElementFieldInfo("CartEntity", "Total", typeof(System.Decimal), false, false, false, false,  (int)CartFieldIndex.Total, 0, 2, 10);
			this.AddElementFieldInfo("CartEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CartEntity", "UserId", typeof(Nullable<System.Guid>), false, true, false, true,  (int)CartFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits CartItemEntity's info objects</summary>
		private void InitCartItemEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CartItemFieldIndex), "CartItemEntity");
			this.AddElementFieldInfo("CartItemEntity", "CartId", typeof(System.Guid), false, true, false, false,  (int)CartItemFieldIndex.CartId, 0, 0, 0);
			this.AddElementFieldInfo("CartItemEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartItemFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CartItemEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CartItemFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CartItemEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)CartItemFieldIndex.Price, 0, 2, 10);
			this.AddElementFieldInfo("CartItemEntity", "ProductId", typeof(System.Guid), false, true, false, false,  (int)CartItemFieldIndex.ProductId, 0, 0, 0);
			this.AddElementFieldInfo("CartItemEntity", "Quantity", typeof(System.Int32), false, false, false, false,  (int)CartItemFieldIndex.Quantity, 0, 0, 10);
			this.AddElementFieldInfo("CartItemEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)CartItemFieldIndex.Subtotal, 0, 2, 10);
			this.AddElementFieldInfo("CartItemEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartItemFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits CartSummaryViewEntity's info objects</summary>
		private void InitCartSummaryViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CartSummaryViewFieldIndex), "CartSummaryViewEntity");
			this.AddElementFieldInfo("CartSummaryViewEntity", "CartId", typeof(System.Guid), false, false, false, false,  (int)CartSummaryViewFieldIndex.CartId, 0, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartSummaryViewFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "Discount", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.Discount, 0, 2, 10);
			this.AddElementFieldInfo("CartSummaryViewEntity", "DiscountCode", typeof(System.String), false, false, false, false,  (int)CartSummaryViewFieldIndex.DiscountCode, 50, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "HoursSinceUpdate", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.HoursSinceUpdate, 0, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "SessionId", typeof(System.String), false, false, false, false,  (int)CartSummaryViewFieldIndex.SessionId, 100, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "Shipping", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.Shipping, 0, 2, 10);
			this.AddElementFieldInfo("CartSummaryViewEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.Subtotal, 0, 2, 10);
			this.AddElementFieldInfo("CartSummaryViewEntity", "Tax", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.Tax, 0, 2, 10);
			this.AddElementFieldInfo("CartSummaryViewEntity", "Total", typeof(System.Decimal), false, false, false, false,  (int)CartSummaryViewFieldIndex.Total, 0, 2, 10);
			this.AddElementFieldInfo("CartSummaryViewEntity", "TotalItems", typeof(System.Int64), false, false, false, false,  (int)CartSummaryViewFieldIndex.TotalItems, 0, 0, 20);
			this.AddElementFieldInfo("CartSummaryViewEntity", "TotalQuantity", typeof(System.Int64), false, false, false, false,  (int)CartSummaryViewFieldIndex.TotalQuantity, 0, 0, 20);
			this.AddElementFieldInfo("CartSummaryViewEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)CartSummaryViewFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "UserEmail", typeof(System.String), false, false, false, false,  (int)CartSummaryViewFieldIndex.UserEmail, 255, 0, 0);
			this.AddElementFieldInfo("CartSummaryViewEntity", "UserId", typeof(System.Guid), false, false, false, false,  (int)CartSummaryViewFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits CategoryEntity's info objects</summary>
		private void InitCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CategoryFieldIndex), "CategoryEntity");
			this.AddElementFieldInfo("CategoryEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)CategoryFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "Description", typeof(System.String), false, false, false, true,  (int)CategoryFieldIndex.Description, 1000, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "DisplayOrder", typeof(System.Int32), false, false, false, false,  (int)CategoryFieldIndex.DisplayOrder, 0, 0, 10);
			this.AddElementFieldInfo("CategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "ImageUrl", typeof(System.String), false, false, false, true,  (int)CategoryFieldIndex.ImageUrl, 500, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)CategoryFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "Level", typeof(System.Int32), false, false, false, false,  (int)CategoryFieldIndex.Level, 0, 0, 10);
			this.AddElementFieldInfo("CategoryEntity", "Name", typeof(System.String), false, false, false, false,  (int)CategoryFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "ParentCategoryId", typeof(Nullable<System.Guid>), false, true, false, true,  (int)CategoryFieldIndex.ParentCategoryId, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "Slug", typeof(System.String), false, false, false, false,  (int)CategoryFieldIndex.Slug, 100, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)CategoryFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits CategoryPerformanceViewEntity's info objects</summary>
		private void InitCategoryPerformanceViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CategoryPerformanceViewFieldIndex), "CategoryPerformanceViewEntity");
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "ActiveProducts", typeof(System.Int64), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.ActiveProducts, 0, 0, 20);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "AverageCategoryRating", typeof(System.Decimal), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.AverageCategoryRating, 0, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "AvgPrice", typeof(System.Decimal), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.AvgPrice, 0, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "CategoryId", typeof(System.Guid), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.CategoryId, 0, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "CategoryName", typeof(System.String), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.CategoryName, 100, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "CategorySlug", typeof(System.String), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.CategorySlug, 100, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "MaxPrice", typeof(System.Decimal), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.MaxPrice, 0, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "MinPrice", typeof(System.Decimal), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.MinPrice, 0, 0, 0);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "TotalProducts", typeof(System.Int64), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.TotalProducts, 0, 0, 20);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "TotalSales", typeof(System.Int64), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.TotalSales, 0, 0, 20);
			this.AddElementFieldInfo("CategoryPerformanceViewEntity", "TotalStock", typeof(System.Int64), false, false, false, false,  (int)CategoryPerformanceViewFieldIndex.TotalStock, 0, 0, 20);
		}

		/// <summary>Inits CouponEntity's info objects</summary>
		private void InitCouponEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CouponFieldIndex), "CouponEntity");
			this.AddElementFieldInfo("CouponEntity", "AppliesToCategories", typeof(System.String[]), false, false, false, true,  (int)CouponFieldIndex.AppliesToCategories, 2147483647, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "AppliesToProducts", typeof(System.String[]), false, false, false, true,  (int)CouponFieldIndex.AppliesToProducts, 2147483647, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "Code", typeof(System.String), false, false, false, false,  (int)CouponFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)CouponFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "Description", typeof(System.String), false, false, false, true,  (int)CouponFieldIndex.Description, 500, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "DiscountType", typeof(System.String), false, false, false, false,  (int)CouponFieldIndex.DiscountType, 20, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "DiscountValue", typeof(System.Decimal), false, false, false, false,  (int)CouponFieldIndex.DiscountValue, 0, 2, 10);
			this.AddElementFieldInfo("CouponEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CouponFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)CouponFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "MaxDiscountAmount", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CouponFieldIndex.MaxDiscountAmount, 0, 2, 10);
			this.AddElementFieldInfo("CouponEntity", "MaxUses", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CouponFieldIndex.MaxUses, 0, 0, 10);
			this.AddElementFieldInfo("CouponEntity", "MaxUsesPerUser", typeof(System.Int32), false, false, false, false,  (int)CouponFieldIndex.MaxUsesPerUser, 0, 0, 10);
			this.AddElementFieldInfo("CouponEntity", "MinOrderAmount", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CouponFieldIndex.MinOrderAmount, 0, 2, 10);
			this.AddElementFieldInfo("CouponEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)CouponFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "UsedCount", typeof(System.Int32), false, false, false, false,  (int)CouponFieldIndex.UsedCount, 0, 0, 10);
			this.AddElementFieldInfo("CouponEntity", "ValidFrom", typeof(System.DateTime), false, false, false, false,  (int)CouponFieldIndex.ValidFrom, 0, 0, 0);
			this.AddElementFieldInfo("CouponEntity", "ValidUntil", typeof(System.DateTime), false, false, false, false,  (int)CouponFieldIndex.ValidUntil, 0, 0, 0);
		}

		/// <summary>Inits CouponUsageEntity's info objects</summary>
		private void InitCouponUsageEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CouponUsageFieldIndex), "CouponUsageEntity");
			this.AddElementFieldInfo("CouponUsageEntity", "CouponId", typeof(System.Guid), false, true, false, false,  (int)CouponUsageFieldIndex.CouponId, 0, 0, 0);
			this.AddElementFieldInfo("CouponUsageEntity", "DiscountAmount", typeof(System.Decimal), false, false, false, false,  (int)CouponUsageFieldIndex.DiscountAmount, 0, 2, 10);
			this.AddElementFieldInfo("CouponUsageEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CouponUsageFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CouponUsageEntity", "OrderId", typeof(System.Guid), false, true, false, false,  (int)CouponUsageFieldIndex.OrderId, 0, 0, 0);
			this.AddElementFieldInfo("CouponUsageEntity", "UsedAt", typeof(System.DateTime), false, false, false, false,  (int)CouponUsageFieldIndex.UsedAt, 0, 0, 0);
			this.AddElementFieldInfo("CouponUsageEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)CouponUsageFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits CustomerOrdersViewEntity's info objects</summary>
		private void InitCustomerOrdersViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomerOrdersViewFieldIndex), "CustomerOrdersViewEntity");
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "AverageOrderValue", typeof(System.Decimal), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.AverageOrderValue, 0, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "CancelledOrders", typeof(System.Int64), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.CancelledOrders, 0, 0, 20);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "CustomerSince", typeof(System.DateTime), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.CustomerSince, 0, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "DeliveredOrders", typeof(System.Int64), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.DeliveredOrders, 0, 0, 20);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "Email", typeof(System.String), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.FirstName, 100, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "FirstOrderDate", typeof(System.DateTime), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.FirstOrderDate, 0, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "LastName", typeof(System.String), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.LastName, 100, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "LastOrderDate", typeof(System.DateTime), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.LastOrderDate, 0, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "LifetimeValue", typeof(System.Decimal), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.LifetimeValue, 0, 0, 0);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "TotalOrders", typeof(System.Int64), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.TotalOrders, 0, 0, 20);
			this.AddElementFieldInfo("CustomerOrdersViewEntity", "UserId", typeof(System.Guid), false, false, false, false,  (int)CustomerOrdersViewFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits OrderEntity's info objects</summary>
		private void InitOrderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderFieldIndex), "OrderEntity");
			this.AddElementFieldInfo("OrderEntity", "BillingAddressLine1", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingAddressLine1, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingAddressLine2", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingAddressLine2, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingCity", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingCity, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingCountry", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingCountry, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingFullName", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingFullName, 200, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingPhone", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingPhone, 20, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingPostalCode", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingPostalCode, 20, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "BillingState", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.BillingState, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "CancellationReason", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.CancellationReason, 500, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "CancelledAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrderFieldIndex.CancelledAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrderFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Currency", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.Currency, 3, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "DeliveredAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrderFieldIndex.DeliveredAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Discount", typeof(System.Decimal), false, false, false, false,  (int)OrderFieldIndex.Discount, 0, 2, 10);
			this.AddElementFieldInfo("OrderEntity", "DiscountCode", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.DiscountCode, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "EstimatedDeliveryDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrderFieldIndex.EstimatedDeliveryDate, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrderFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Notes", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.Notes, 1000, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "OrderNumber", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.OrderNumber, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "PaymentMethod", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.PaymentMethod, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "PaymentStatus", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.PaymentStatus, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "PaymentTransactionId", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.PaymentTransactionId, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingAddressLine1", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingAddressLine1, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingAddressLine2", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.ShippingAddressLine2, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingCarrier", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.ShippingCarrier, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingCity", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingCity, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingCost", typeof(System.Decimal), false, false, false, false,  (int)OrderFieldIndex.ShippingCost, 0, 2, 10);
			this.AddElementFieldInfo("OrderEntity", "ShippingCountry", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingCountry, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingFullName", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingFullName, 200, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingMethod", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingMethod, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingPhone", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingPhone, 20, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingPostalCode", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingPostalCode, 20, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "ShippingState", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.ShippingState, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Status", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.Status, 50, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)OrderFieldIndex.Subtotal, 0, 2, 10);
			this.AddElementFieldInfo("OrderEntity", "Tax", typeof(System.Decimal), false, false, false, false,  (int)OrderFieldIndex.Tax, 0, 2, 10);
			this.AddElementFieldInfo("OrderEntity", "Total", typeof(System.Decimal), false, false, false, false,  (int)OrderFieldIndex.Total, 0, 2, 10);
			this.AddElementFieldInfo("OrderEntity", "TrackingNumber", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.TrackingNumber, 100, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrderFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)OrderFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits OrderItemEntity's info objects</summary>
		private void InitOrderItemEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderItemFieldIndex), "OrderItemEntity");
			this.AddElementFieldInfo("OrderItemEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrderItemFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrderItemFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "OrderId", typeof(System.Guid), false, true, false, false,  (int)OrderItemFieldIndex.OrderId, 0, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)OrderItemFieldIndex.Price, 0, 2, 10);
			this.AddElementFieldInfo("OrderItemEntity", "ProductId", typeof(System.Guid), false, true, false, false,  (int)OrderItemFieldIndex.ProductId, 0, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "ProductImageUrl", typeof(System.String), false, false, false, true,  (int)OrderItemFieldIndex.ProductImageUrl, 500, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "ProductName", typeof(System.String), false, false, false, false,  (int)OrderItemFieldIndex.ProductName, 255, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "ProductSku", typeof(System.String), false, false, false, false,  (int)OrderItemFieldIndex.ProductSku, 100, 0, 0);
			this.AddElementFieldInfo("OrderItemEntity", "Quantity", typeof(System.Int32), false, false, false, false,  (int)OrderItemFieldIndex.Quantity, 0, 0, 10);
			this.AddElementFieldInfo("OrderItemEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)OrderItemFieldIndex.Subtotal, 0, 2, 10);
		}

		/// <summary>Inits OrderSummaryViewEntity's info objects</summary>
		private void InitOrderSummaryViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderSummaryViewFieldIndex), "OrderSummaryViewEntity");
			this.AddElementFieldInfo("OrderSummaryViewEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrderSummaryViewFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Currency", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Currency, 3, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "CustomerName", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.CustomerName, 1073741824, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "DeliveredAt", typeof(System.DateTime), false, false, false, false,  (int)OrderSummaryViewFieldIndex.DeliveredAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Discount", typeof(System.Decimal), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Discount, 0, 2, 10);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "EstimatedDeliveryDate", typeof(System.DateTime), false, false, false, false,  (int)OrderSummaryViewFieldIndex.EstimatedDeliveryDate, 0, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Id", typeof(System.Guid), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "OrderNumber", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.OrderNumber, 50, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "PaymentMethod", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.PaymentMethod, 50, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "PaymentStatus", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.PaymentStatus, 50, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingCarrier", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingCarrier, 100, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingCity", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingCity, 100, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingCost", typeof(System.Decimal), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingCost, 0, 2, 10);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingCountry", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingCountry, 100, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingFullName", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingFullName, 200, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "ShippingState", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.ShippingState, 100, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Status", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Status, 50, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Subtotal", typeof(System.Decimal), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Subtotal, 0, 2, 10);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Tax", typeof(System.Decimal), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Tax, 0, 2, 10);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "Total", typeof(System.Decimal), false, false, false, false,  (int)OrderSummaryViewFieldIndex.Total, 0, 2, 10);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "TotalItems", typeof(System.Int64), false, false, false, false,  (int)OrderSummaryViewFieldIndex.TotalItems, 0, 0, 20);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "TotalQuantity", typeof(System.Int64), false, false, false, false,  (int)OrderSummaryViewFieldIndex.TotalQuantity, 0, 0, 20);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "TrackingNumber", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.TrackingNumber, 100, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrderSummaryViewFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "UserEmail", typeof(System.String), false, false, false, false,  (int)OrderSummaryViewFieldIndex.UserEmail, 255, 0, 0);
			this.AddElementFieldInfo("OrderSummaryViewEntity", "UserId", typeof(System.Guid), false, false, false, false,  (int)OrderSummaryViewFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits PaymentEntity's info objects</summary>
		private void InitPaymentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PaymentFieldIndex), "PaymentEntity");
			this.AddElementFieldInfo("PaymentEntity", "Amount", typeof(System.Decimal), false, false, false, false,  (int)PaymentFieldIndex.Amount, 0, 2, 10);
			this.AddElementFieldInfo("PaymentEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)PaymentFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "Currency", typeof(System.String), false, false, false, false,  (int)PaymentFieldIndex.Currency, 3, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "FailureReason", typeof(System.String), false, false, false, true,  (int)PaymentFieldIndex.FailureReason, 500, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)PaymentFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "OrderId", typeof(System.Guid), false, true, false, false,  (int)PaymentFieldIndex.OrderId, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "PaidAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PaymentFieldIndex.PaidAt, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "PaymentMethod", typeof(System.String), false, false, false, false,  (int)PaymentFieldIndex.PaymentMethod, 50, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "PaymentProvider", typeof(System.String), false, false, false, false,  (int)PaymentFieldIndex.PaymentProvider, 50, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "PaypalOrderId", typeof(System.String), false, false, false, true,  (int)PaymentFieldIndex.PaypalOrderId, 255, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "RefundAmount", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)PaymentFieldIndex.RefundAmount, 0, 2, 10);
			this.AddElementFieldInfo("PaymentEntity", "RefundedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PaymentFieldIndex.RefundedAt, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "RefundReason", typeof(System.String), false, false, false, true,  (int)PaymentFieldIndex.RefundReason, 500, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "Status", typeof(System.String), false, false, false, false,  (int)PaymentFieldIndex.Status, 50, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "StripePaymentIntentId", typeof(System.String), false, false, false, true,  (int)PaymentFieldIndex.StripePaymentIntentId, 255, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "TransactionId", typeof(System.String), false, false, false, true,  (int)PaymentFieldIndex.TransactionId, 255, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)PaymentFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("PaymentEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)PaymentFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits ProductEntity's info objects</summary>
		private void InitProductEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProductFieldIndex), "ProductEntity");
			this.AddElementFieldInfo("ProductEntity", "AverageRating", typeof(System.Decimal), false, false, false, false,  (int)ProductFieldIndex.AverageRating, 0, 2, 3);
			this.AddElementFieldInfo("ProductEntity", "Brand", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.Brand, 100, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "CategoryId", typeof(System.Guid), false, true, false, false,  (int)ProductFieldIndex.CategoryId, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)ProductFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Currency", typeof(System.String), false, false, false, false,  (int)ProductFieldIndex.Currency, 3, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Description", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.Description, 5000, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Dimensions", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.Dimensions, 100, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "DiscountPercentage", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)ProductFieldIndex.DiscountPercentage, 0, 2, 5);
			this.AddElementFieldInfo("ProductEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)ProductFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)ProductFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "IsFeatured", typeof(System.Boolean), false, false, false, false,  (int)ProductFieldIndex.IsFeatured, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "LowStockThreshold", typeof(System.Int32), false, false, false, false,  (int)ProductFieldIndex.LowStockThreshold, 0, 0, 10);
			this.AddElementFieldInfo("ProductEntity", "MetaDescription", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.MetaDescription, 500, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "MetaKeywords", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.MetaKeywords, 500, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "MetaTitle", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.MetaTitle, 255, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Name", typeof(System.String), false, false, false, false,  (int)ProductFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "OriginalPrice", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)ProductFieldIndex.OriginalPrice, 0, 2, 10);
			this.AddElementFieldInfo("ProductEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)ProductFieldIndex.Price, 0, 2, 10);
			this.AddElementFieldInfo("ProductEntity", "ShortDescription", typeof(System.String), false, false, false, true,  (int)ProductFieldIndex.ShortDescription, 500, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Sku", typeof(System.String), false, false, false, false,  (int)ProductFieldIndex.Sku, 100, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Slug", typeof(System.String), false, false, false, false,  (int)ProductFieldIndex.Slug, 255, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "StockQuantity", typeof(System.Int32), false, false, false, false,  (int)ProductFieldIndex.StockQuantity, 0, 0, 10);
			this.AddElementFieldInfo("ProductEntity", "TotalReviews", typeof(System.Int32), false, false, false, false,  (int)ProductFieldIndex.TotalReviews, 0, 0, 10);
			this.AddElementFieldInfo("ProductEntity", "TotalSales", typeof(System.Int32), false, false, false, false,  (int)ProductFieldIndex.TotalSales, 0, 0, 10);
			this.AddElementFieldInfo("ProductEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)ProductFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ProductEntity", "Weight", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)ProductFieldIndex.Weight, 0, 2, 10);
		}

		/// <summary>Inits ProductImageEntity's info objects</summary>
		private void InitProductImageEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProductImageFieldIndex), "ProductImageEntity");
			this.AddElementFieldInfo("ProductImageEntity", "AltText", typeof(System.String), false, false, false, true,  (int)ProductImageFieldIndex.AltText, 255, 0, 0);
			this.AddElementFieldInfo("ProductImageEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)ProductImageFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ProductImageEntity", "DisplayOrder", typeof(System.Int32), false, false, false, false,  (int)ProductImageFieldIndex.DisplayOrder, 0, 0, 10);
			this.AddElementFieldInfo("ProductImageEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)ProductImageFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ProductImageEntity", "ImageUrl", typeof(System.String), false, false, false, false,  (int)ProductImageFieldIndex.ImageUrl, 500, 0, 0);
			this.AddElementFieldInfo("ProductImageEntity", "IsPrimary", typeof(System.Boolean), false, false, false, false,  (int)ProductImageFieldIndex.IsPrimary, 0, 0, 0);
			this.AddElementFieldInfo("ProductImageEntity", "ProductId", typeof(System.Guid), false, true, false, false,  (int)ProductImageFieldIndex.ProductId, 0, 0, 0);
		}

		/// <summary>Inits ProductInventoryViewEntity's info objects</summary>
		private void InitProductInventoryViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProductInventoryViewFieldIndex), "ProductInventoryViewEntity");
			this.AddElementFieldInfo("ProductInventoryViewEntity", "AverageRating", typeof(System.Decimal), false, false, false, false,  (int)ProductInventoryViewFieldIndex.AverageRating, 0, 2, 3);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "CategoryName", typeof(System.String), false, false, false, false,  (int)ProductInventoryViewFieldIndex.CategoryName, 100, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "CategorySlug", typeof(System.String), false, false, false, false,  (int)ProductInventoryViewFieldIndex.CategorySlug, 100, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)ProductInventoryViewFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "DiscountPercentage", typeof(System.Decimal), false, false, false, false,  (int)ProductInventoryViewFieldIndex.DiscountPercentage, 0, 2, 5);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "Id", typeof(System.Guid), false, false, false, false,  (int)ProductInventoryViewFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)ProductInventoryViewFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "IsFeatured", typeof(System.Boolean), false, false, false, false,  (int)ProductInventoryViewFieldIndex.IsFeatured, 0, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "LowStockThreshold", typeof(System.Int32), false, false, false, false,  (int)ProductInventoryViewFieldIndex.LowStockThreshold, 0, 0, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "Name", typeof(System.String), false, false, false, false,  (int)ProductInventoryViewFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "OriginalPrice", typeof(System.Decimal), false, false, false, false,  (int)ProductInventoryViewFieldIndex.OriginalPrice, 0, 2, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)ProductInventoryViewFieldIndex.Price, 0, 2, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "Sku", typeof(System.String), false, false, false, false,  (int)ProductInventoryViewFieldIndex.Sku, 100, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "StockQuantity", typeof(System.Int32), false, false, false, false,  (int)ProductInventoryViewFieldIndex.StockQuantity, 0, 0, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "StockStatus", typeof(System.String), false, false, false, false,  (int)ProductInventoryViewFieldIndex.StockStatus, 1073741824, 0, 0);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "TotalReviews", typeof(System.Int32), false, false, false, false,  (int)ProductInventoryViewFieldIndex.TotalReviews, 0, 0, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "TotalSales", typeof(System.Int32), false, false, false, false,  (int)ProductInventoryViewFieldIndex.TotalSales, 0, 0, 10);
			this.AddElementFieldInfo("ProductInventoryViewEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)ProductInventoryViewFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits ProductRatingViewEntity's info objects</summary>
		private void InitProductRatingViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProductRatingViewFieldIndex), "ProductRatingViewEntity");
			this.AddElementFieldInfo("ProductRatingViewEntity", "AverageRating", typeof(System.Decimal), false, false, false, false,  (int)ProductRatingViewFieldIndex.AverageRating, 0, 2, 3);
			this.AddElementFieldInfo("ProductRatingViewEntity", "CalculatedAvgRating", typeof(System.Decimal), false, false, false, false,  (int)ProductRatingViewFieldIndex.CalculatedAvgRating, 0, 0, 0);
			this.AddElementFieldInfo("ProductRatingViewEntity", "FiveStarCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.FiveStarCount, 0, 0, 20);
			this.AddElementFieldInfo("ProductRatingViewEntity", "FourStarCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.FourStarCount, 0, 0, 20);
			this.AddElementFieldInfo("ProductRatingViewEntity", "OneStarCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.OneStarCount, 0, 0, 20);
			this.AddElementFieldInfo("ProductRatingViewEntity", "ProductId", typeof(System.Guid), false, false, false, false,  (int)ProductRatingViewFieldIndex.ProductId, 0, 0, 0);
			this.AddElementFieldInfo("ProductRatingViewEntity", "ProductName", typeof(System.String), false, false, false, false,  (int)ProductRatingViewFieldIndex.ProductName, 255, 0, 0);
			this.AddElementFieldInfo("ProductRatingViewEntity", "ThreeStarCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.ThreeStarCount, 0, 0, 20);
			this.AddElementFieldInfo("ProductRatingViewEntity", "TotalReviews", typeof(System.Int32), false, false, false, false,  (int)ProductRatingViewFieldIndex.TotalReviews, 0, 0, 10);
			this.AddElementFieldInfo("ProductRatingViewEntity", "TwoStarCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.TwoStarCount, 0, 0, 20);
			this.AddElementFieldInfo("ProductRatingViewEntity", "VerifiedPurchaseCount", typeof(System.Int64), false, false, false, false,  (int)ProductRatingViewFieldIndex.VerifiedPurchaseCount, 0, 0, 20);
		}

		/// <summary>Inits ReviewEntity's info objects</summary>
		private void InitReviewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ReviewFieldIndex), "ReviewEntity");
			this.AddElementFieldInfo("ReviewEntity", "Comment", typeof(System.String), false, false, false, true,  (int)ReviewFieldIndex.Comment, 2000, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)ReviewFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "HelpfulCount", typeof(System.Int32), false, false, false, false,  (int)ReviewFieldIndex.HelpfulCount, 0, 0, 10);
			this.AddElementFieldInfo("ReviewEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)ReviewFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "IsApproved", typeof(System.Boolean), false, false, false, false,  (int)ReviewFieldIndex.IsApproved, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "IsVerifiedPurchase", typeof(System.Boolean), false, false, false, false,  (int)ReviewFieldIndex.IsVerifiedPurchase, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "OrderId", typeof(Nullable<System.Guid>), false, true, false, true,  (int)ReviewFieldIndex.OrderId, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "ProductId", typeof(System.Guid), false, true, false, false,  (int)ReviewFieldIndex.ProductId, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "Rating", typeof(System.Int32), false, false, false, false,  (int)ReviewFieldIndex.Rating, 0, 0, 10);
			this.AddElementFieldInfo("ReviewEntity", "Title", typeof(System.String), false, false, false, true,  (int)ReviewFieldIndex.Title, 200, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "UnhelpfulCount", typeof(System.Int32), false, false, false, false,  (int)ReviewFieldIndex.UnhelpfulCount, 0, 0, 10);
			this.AddElementFieldInfo("ReviewEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)ReviewFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("ReviewEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)ReviewFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits SalesPerformanceViewEntity's info objects</summary>
		private void InitSalesPerformanceViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SalesPerformanceViewFieldIndex), "SalesPerformanceViewEntity");
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "AverageOrderValue", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.AverageOrderValue, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "OrdersCount", typeof(System.Int64), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.OrdersCount, 0, 0, 20);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "SaleDate", typeof(System.DateTime), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.SaleDate, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalDiscounts", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalDiscounts, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalItemsSold", typeof(System.Int64), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalItemsSold, 0, 0, 20);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalRevenue", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalRevenue, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalShipping", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalShipping, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalSubtotal", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalSubtotal, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "TotalTax", typeof(System.Decimal), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.TotalTax, 0, 0, 0);
			this.AddElementFieldInfo("SalesPerformanceViewEntity", "UniqueCustomers", typeof(System.Int64), false, false, false, false,  (int)SalesPerformanceViewFieldIndex.UniqueCustomers, 0, 0, 20);
		}

		/// <summary>Inits SavedPaymentMethodEntity's info objects</summary>
		private void InitSavedPaymentMethodEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SavedPaymentMethodFieldIndex), "SavedPaymentMethodEntity");
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingAddressLine1", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.BillingAddressLine1, 255, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingCity", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.BillingCity, 100, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingCountry", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.BillingCountry, 100, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingName", typeof(System.String), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.BillingName, 200, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingPostalCode", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.BillingPostalCode, 20, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "BillingState", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.BillingState, 100, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "CardBrand", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.CardBrand, 50, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "CardExpMonth", typeof(Nullable<System.Int32>), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.CardExpMonth, 0, 0, 10);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "CardExpYear", typeof(Nullable<System.Int32>), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.CardExpYear, 0, 0, 10);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "CardLastFour", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.CardLastFour, 4, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)SavedPaymentMethodFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "IsDefault", typeof(System.Boolean), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.IsDefault, 0, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "PaymentMethodType", typeof(System.String), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.PaymentMethodType, 50, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "PaymentProvider", typeof(System.String), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.PaymentProvider, 50, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "StripePaymentMethodId", typeof(System.String), false, false, false, true,  (int)SavedPaymentMethodFieldIndex.StripePaymentMethodId, 255, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)SavedPaymentMethodFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("SavedPaymentMethodEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)SavedPaymentMethodFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Email", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "EmailVerificationToken", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.EmailVerificationToken, 500, 0, 0);
			this.AddElementFieldInfo("UserEntity", "FailedLoginAttempts", typeof(System.Int32), false, false, false, false,  (int)UserFieldIndex.FailedLoginAttempts, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.FirstName, 100, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)UserFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "IsEmailVerified", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsEmailVerified, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastLoginAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LastLoginAt, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.LastName, 100, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LockoutEnd", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LockoutEnd, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 500, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordResetExpires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.PasswordResetExpires, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordResetToken", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.PasswordResetToken, 500, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PhoneNumber", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.PhoneNumber, 20, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Role", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Role, 50, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits WishlistEntity's info objects</summary>
		private void InitWishlistEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(WishlistFieldIndex), "WishlistEntity");
			this.AddElementFieldInfo("WishlistEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)WishlistFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)WishlistFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "IsDefault", typeof(System.Boolean), false, false, false, false,  (int)WishlistFieldIndex.IsDefault, 0, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "IsPublic", typeof(System.Boolean), false, false, false, false,  (int)WishlistFieldIndex.IsPublic, 0, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "Name", typeof(System.String), false, false, false, false,  (int)WishlistFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "UpdatedAt", typeof(System.DateTime), false, false, false, false,  (int)WishlistFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("WishlistEntity", "UserId", typeof(System.Guid), false, true, false, false,  (int)WishlistFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits WishlistItemEntity's info objects</summary>
		private void InitWishlistItemEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(WishlistItemFieldIndex), "WishlistItemEntity");
			this.AddElementFieldInfo("WishlistItemEntity", "AddedAt", typeof(System.DateTime), false, false, false, false,  (int)WishlistItemFieldIndex.AddedAt, 0, 0, 0);
			this.AddElementFieldInfo("WishlistItemEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)WishlistItemFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("WishlistItemEntity", "Notes", typeof(System.String), false, false, false, true,  (int)WishlistItemFieldIndex.Notes, 500, 0, 0);
			this.AddElementFieldInfo("WishlistItemEntity", "ProductId", typeof(System.Guid), false, true, false, false,  (int)WishlistItemFieldIndex.ProductId, 0, 0, 0);
			this.AddElementFieldInfo("WishlistItemEntity", "WishlistId", typeof(System.Guid), false, true, false, false,  (int)WishlistItemFieldIndex.WishlistId, 0, 0, 0);
		}
	}
}