//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ECommerce.Data.HelperClasses;
using ECommerce.Data.FactoryClasses;
using ECommerce.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ECommerce.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'CartItem'.<br/><br/></summary>
	[Serializable]
	public partial class CartItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private CartEntity _cart;
		private ProductEntity _product;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CartItemEntityStaticMetaData _staticMetaData = new CartItemEntityStaticMetaData();
		private static CartItemRelations _relationsFactory = new CartItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Cart</summary>
			public static readonly string Cart = "Cart";
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CartItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CartItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("CartItemEntity", InheritanceHierarchyType.None, false, (int)ECommerce.Data.EntityType.CartItemEntity, typeof(CartItemEntity), typeof(CartItemEntityFactory), false);
				AddNavigatorMetaData<CartItemEntity, CartEntity>("Cart", "CartItems", (a, b) => a._cart = b, a => a._cart, (a, b) => a.Cart = b, ECommerce.Data.RelationClasses.StaticCartItemRelations.CartEntityUsingCartIdStatic, ()=>new CartItemRelations().CartEntityUsingCartId, null, new int[] { (int)CartItemFieldIndex.CartId }, null, true, (int)ECommerce.Data.EntityType.CartEntity);
				AddNavigatorMetaData<CartItemEntity, ProductEntity>("Product", "CartItems", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, ECommerce.Data.RelationClasses.StaticCartItemRelations.ProductEntityUsingProductIdStatic, ()=>new CartItemRelations().ProductEntityUsingProductId, null, new int[] { (int)CartItemFieldIndex.ProductId }, null, true, (int)ECommerce.Data.EntityType.ProductEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CartItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public CartItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CartItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CartItemEntity</param>
		public CartItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CartItem which data should be fetched into this CartItem object</param>
		public CartItemEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CartItem which data should be fetched into this CartItem object</param>
		/// <param name="validator">The custom validator object for this CartItemEntity</param>
		public CartItemEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CartItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Cart' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCart() { return CreateRelationInfoForNavigator("Cart"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CartItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CartItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Cart' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCart { get { return _staticMetaData.GetPrefetchPathElement("Cart", CommonEntityBase.CreateEntityCollection<CartEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>The CartId property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."cart_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CartId
		{
			get { return (System.Guid)GetValue((int)CartItemFieldIndex.CartId, true); }
			set { SetValue((int)CartItemFieldIndex.CartId, value); }
		}

		/// <summary>The CreatedAt property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)CartItemFieldIndex.CreatedAt, true); }
			set { SetValue((int)CartItemFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)CartItemFieldIndex.Id, true); }
			set { SetValue((int)CartItemFieldIndex.Id, value); }
		}

		/// <summary>The Price property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)CartItemFieldIndex.Price, true); }
			set { SetValue((int)CartItemFieldIndex.Price, value); }
		}

		/// <summary>The ProductId property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)CartItemFieldIndex.ProductId, true); }
			set { SetValue((int)CartItemFieldIndex.ProductId, value); }
		}

		/// <summary>The Quantity property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Quantity
		{
			get { return (System.Int32)GetValue((int)CartItemFieldIndex.Quantity, true); }
			set { SetValue((int)CartItemFieldIndex.Quantity, value); }
		}

		/// <summary>The Subtotal property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."subtotal".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Subtotal
		{
			get { return (System.Decimal)GetValue((int)CartItemFieldIndex.Subtotal, true); }
			set { SetValue((int)CartItemFieldIndex.Subtotal, value); }
		}

		/// <summary>The UpdatedAt property of the Entity CartItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "cart_items"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)CartItemFieldIndex.UpdatedAt, true); }
			set { SetValue((int)CartItemFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets / sets related entity of type 'CartEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CartEntity Cart
		{
			get { return _cart; }
			set { SetSingleRelatedEntityNavigator(value, "Cart"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ECommerce.Data
{
	public enum CartItemFieldIndex
	{
		///<summary>CartId. </summary>
		CartId,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Price. </summary>
		Price,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>Subtotal. </summary>
		Subtotal,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ECommerce.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CartItem. </summary>
	public partial class CartItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between CartItemEntity and CartEntity over the m:1 relation they have, using the relation between the fields: CartItem.CartId - Cart.Id</summary>
		public virtual IEntityRelation CartEntityUsingCartId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Cart", false, new[] { CartFields.Id, CartItemFields.CartId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CartItemEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: CartItem.ProductId - Product.Id</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.Id, CartItemFields.ProductId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCartItemRelations
	{
		internal static readonly IEntityRelation CartEntityUsingCartIdStatic = new CartItemRelations().CartEntityUsingCartId;
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new CartItemRelations().ProductEntityUsingProductId;

		/// <summary>CTor</summary>
		static StaticCartItemRelations() { }
	}
}
