//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ECommerce.Data.HelperClasses;
using ECommerce.Data.FactoryClasses;
using ECommerce.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ECommerce.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Product'.<br/><br/></summary>
	[Serializable]
	public partial class ProductEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<CartItemEntity> _cartItems;
		private EntityCollection<OrderItemEntity> _orderItems;
		private EntityCollection<ProductImageEntity> _productImages;
		private EntityCollection<ReviewEntity> _reviews;
		private EntityCollection<WishlistItemEntity> _wishlistItems;
		private CategoryEntity _category;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ProductEntityStaticMetaData _staticMetaData = new ProductEntityStaticMetaData();
		private static ProductRelations _relationsFactory = new ProductRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Category</summary>
			public static readonly string Category = "Category";
			/// <summary>Member name CartItems</summary>
			public static readonly string CartItems = "CartItems";
			/// <summary>Member name OrderItems</summary>
			public static readonly string OrderItems = "OrderItems";
			/// <summary>Member name ProductImages</summary>
			public static readonly string ProductImages = "ProductImages";
			/// <summary>Member name Reviews</summary>
			public static readonly string Reviews = "Reviews";
			/// <summary>Member name WishlistItems</summary>
			public static readonly string WishlistItems = "WishlistItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductEntity", InheritanceHierarchyType.None, false, (int)ECommerce.Data.EntityType.ProductEntity, typeof(ProductEntity), typeof(ProductEntityFactory), false);
				AddNavigatorMetaData<ProductEntity, EntityCollection<CartItemEntity>>("CartItems", a => a._cartItems, (a, b) => a._cartItems = b, a => a.CartItems, () => new ProductRelations().CartItemEntityUsingProductId, typeof(CartItemEntity), (int)ECommerce.Data.EntityType.CartItemEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<OrderItemEntity>>("OrderItems", a => a._orderItems, (a, b) => a._orderItems = b, a => a.OrderItems, () => new ProductRelations().OrderItemEntityUsingProductId, typeof(OrderItemEntity), (int)ECommerce.Data.EntityType.OrderItemEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductImageEntity>>("ProductImages", a => a._productImages, (a, b) => a._productImages = b, a => a.ProductImages, () => new ProductRelations().ProductImageEntityUsingProductId, typeof(ProductImageEntity), (int)ECommerce.Data.EntityType.ProductImageEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ReviewEntity>>("Reviews", a => a._reviews, (a, b) => a._reviews = b, a => a.Reviews, () => new ProductRelations().ReviewEntityUsingProductId, typeof(ReviewEntity), (int)ECommerce.Data.EntityType.ReviewEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<WishlistItemEntity>>("WishlistItems", a => a._wishlistItems, (a, b) => a._wishlistItems = b, a => a.WishlistItems, () => new ProductRelations().WishlistItemEntityUsingProductId, typeof(WishlistItemEntity), (int)ECommerce.Data.EntityType.WishlistItemEntity);
				AddNavigatorMetaData<ProductEntity, CategoryEntity>("Category", "Products", (a, b) => a._category = b, a => a._category, (a, b) => a.Category = b, ECommerce.Data.RelationClasses.StaticProductRelations.CategoryEntityUsingCategoryIdStatic, ()=>new ProductRelations().CategoryEntityUsingCategoryId, null, new int[] { (int)ProductFieldIndex.CategoryId }, null, true, (int)ECommerce.Data.EntityType.CategoryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductEntity</param>
		public ProductEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Product which data should be fetched into this Product object</param>
		public ProductEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Product which data should be fetched into this Product object</param>
		/// <param name="validator">The custom validator object for this ProductEntity</param>
		public ProductEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CartItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCartItems() { return CreateRelationInfoForNavigator("CartItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderItems() { return CreateRelationInfoForNavigator("OrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductImage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductImages() { return CreateRelationInfoForNavigator("ProductImages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Review' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReviews() { return CreateRelationInfoForNavigator("Reviews"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WishlistItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWishlistItems() { return CreateRelationInfoForNavigator("WishlistItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Category' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCategory() { return CreateRelationInfoForNavigator("Category"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CartItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCartItems { get { return _staticMetaData.GetPrefetchPathElement("CartItems", CommonEntityBase.CreateEntityCollection<CartItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderItems { get { return _staticMetaData.GetPrefetchPathElement("OrderItems", CommonEntityBase.CreateEntityCollection<OrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductImage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductImages { get { return _staticMetaData.GetPrefetchPathElement("ProductImages", CommonEntityBase.CreateEntityCollection<ProductImageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Review' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReviews { get { return _staticMetaData.GetPrefetchPathElement("Reviews", CommonEntityBase.CreateEntityCollection<ReviewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WishlistItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWishlistItems { get { return _staticMetaData.GetPrefetchPathElement("WishlistItems", CommonEntityBase.CreateEntityCollection<WishlistItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Category' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCategory { get { return _staticMetaData.GetPrefetchPathElement("Category", CommonEntityBase.CreateEntityCollection<CategoryEntity>()); } }

		/// <summary>The AverageRating property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."average_rating".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 3, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal AverageRating
		{
			get { return (System.Decimal)GetValue((int)ProductFieldIndex.AverageRating, true); }
			set { SetValue((int)ProductFieldIndex.AverageRating, value); }
		}

		/// <summary>The Brand property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."brand".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Brand
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Brand, true); }
			set { SetValue((int)ProductFieldIndex.Brand, value); }
		}

		/// <summary>The CategoryId property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."category_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CategoryId
		{
			get { return (System.Guid)GetValue((int)ProductFieldIndex.CategoryId, true); }
			set { SetValue((int)ProductFieldIndex.CategoryId, value); }
		}

		/// <summary>The CreatedAt property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ProductFieldIndex.CreatedAt, true); }
			set { SetValue((int)ProductFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Currency property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."currency".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 3.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Currency
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Currency, true); }
			set { SetValue((int)ProductFieldIndex.Currency, value); }
		}

		/// <summary>The Description property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 5000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Description, true); }
			set { SetValue((int)ProductFieldIndex.Description, value); }
		}

		/// <summary>The Dimensions property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."dimensions".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Dimensions
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Dimensions, true); }
			set { SetValue((int)ProductFieldIndex.Dimensions, value); }
		}

		/// <summary>The DiscountPercentage property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."discount_percentage".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 5, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> DiscountPercentage
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.DiscountPercentage, false); }
			set { SetValue((int)ProductFieldIndex.DiscountPercentage, value); }
		}

		/// <summary>The Id property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ProductFieldIndex.Id, true); }
			set { SetValue((int)ProductFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)ProductFieldIndex.IsActive, true); }
			set { SetValue((int)ProductFieldIndex.IsActive, value); }
		}

		/// <summary>The IsFeatured property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."is_featured".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsFeatured
		{
			get { return (System.Boolean)GetValue((int)ProductFieldIndex.IsFeatured, true); }
			set { SetValue((int)ProductFieldIndex.IsFeatured, value); }
		}

		/// <summary>The LowStockThreshold property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."low_stock_threshold".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 LowStockThreshold
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.LowStockThreshold, true); }
			set { SetValue((int)ProductFieldIndex.LowStockThreshold, value); }
		}

		/// <summary>The MetaDescription property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."meta_description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MetaDescription
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.MetaDescription, true); }
			set { SetValue((int)ProductFieldIndex.MetaDescription, value); }
		}

		/// <summary>The MetaKeywords property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."meta_keywords".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MetaKeywords
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.MetaKeywords, true); }
			set { SetValue((int)ProductFieldIndex.MetaKeywords, value); }
		}

		/// <summary>The MetaTitle property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."meta_title".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MetaTitle
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.MetaTitle, true); }
			set { SetValue((int)ProductFieldIndex.MetaTitle, value); }
		}

		/// <summary>The Name property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Name, true); }
			set { SetValue((int)ProductFieldIndex.Name, value); }
		}

		/// <summary>The OriginalPrice property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."original_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> OriginalPrice
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.OriginalPrice, false); }
			set { SetValue((int)ProductFieldIndex.OriginalPrice, value); }
		}

		/// <summary>The Price property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)ProductFieldIndex.Price, true); }
			set { SetValue((int)ProductFieldIndex.Price, value); }
		}

		/// <summary>The ShortDescription property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."short_description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ShortDescription
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.ShortDescription, true); }
			set { SetValue((int)ProductFieldIndex.ShortDescription, value); }
		}

		/// <summary>The Sku property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."sku".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Sku
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Sku, true); }
			set { SetValue((int)ProductFieldIndex.Sku, value); }
		}

		/// <summary>The Slug property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."slug".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Slug
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Slug, true); }
			set { SetValue((int)ProductFieldIndex.Slug, value); }
		}

		/// <summary>The StockQuantity property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."stock_quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 StockQuantity
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.StockQuantity, true); }
			set { SetValue((int)ProductFieldIndex.StockQuantity, value); }
		}

		/// <summary>The TotalReviews property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."total_reviews".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TotalReviews
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.TotalReviews, true); }
			set { SetValue((int)ProductFieldIndex.TotalReviews, value); }
		}

		/// <summary>The TotalSales property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."total_sales".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TotalSales
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.TotalSales, true); }
			set { SetValue((int)ProductFieldIndex.TotalSales, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)ProductFieldIndex.UpdatedAt, true); }
			set { SetValue((int)ProductFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The Weight property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."weight".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Weight
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.Weight, false); }
			set { SetValue((int)ProductFieldIndex.Weight, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CartItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CartItemEntity))]
		public virtual EntityCollection<CartItemEntity> CartItems { get { return GetOrCreateEntityCollection<CartItemEntity, CartItemEntityFactory>("Product", true, false, ref _cartItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderItemEntity))]
		public virtual EntityCollection<OrderItemEntity> OrderItems { get { return GetOrCreateEntityCollection<OrderItemEntity, OrderItemEntityFactory>("Product", true, false, ref _orderItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductImageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductImageEntity))]
		public virtual EntityCollection<ProductImageEntity> ProductImages { get { return GetOrCreateEntityCollection<ProductImageEntity, ProductImageEntityFactory>("Product", true, false, ref _productImages); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ReviewEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ReviewEntity))]
		public virtual EntityCollection<ReviewEntity> Reviews { get { return GetOrCreateEntityCollection<ReviewEntity, ReviewEntityFactory>("Product", true, false, ref _reviews); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WishlistItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WishlistItemEntity))]
		public virtual EntityCollection<WishlistItemEntity> WishlistItems { get { return GetOrCreateEntityCollection<WishlistItemEntity, WishlistItemEntityFactory>("Product", true, false, ref _wishlistItems); } }

		/// <summary>Gets / sets related entity of type 'CategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CategoryEntity Category
		{
			get { return _category; }
			set { SetSingleRelatedEntityNavigator(value, "Category"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ECommerce.Data
{
	public enum ProductFieldIndex
	{
		///<summary>AverageRating. </summary>
		AverageRating,
		///<summary>Brand. </summary>
		Brand,
		///<summary>CategoryId. </summary>
		CategoryId,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Currency. </summary>
		Currency,
		///<summary>Description. </summary>
		Description,
		///<summary>Dimensions. </summary>
		Dimensions,
		///<summary>DiscountPercentage. </summary>
		DiscountPercentage,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>IsFeatured. </summary>
		IsFeatured,
		///<summary>LowStockThreshold. </summary>
		LowStockThreshold,
		///<summary>MetaDescription. </summary>
		MetaDescription,
		///<summary>MetaKeywords. </summary>
		MetaKeywords,
		///<summary>MetaTitle. </summary>
		MetaTitle,
		///<summary>Name. </summary>
		Name,
		///<summary>OriginalPrice. </summary>
		OriginalPrice,
		///<summary>Price. </summary>
		Price,
		///<summary>ShortDescription. </summary>
		ShortDescription,
		///<summary>Sku. </summary>
		Sku,
		///<summary>Slug. </summary>
		Slug,
		///<summary>StockQuantity. </summary>
		StockQuantity,
		///<summary>TotalReviews. </summary>
		TotalReviews,
		///<summary>TotalSales. </summary>
		TotalSales,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>Weight. </summary>
		Weight,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ECommerce.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Product. </summary>
	public partial class ProductRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProductEntity and CartItemEntity over the 1:n relation they have, using the relation between the fields: Product.Id - CartItem.ProductId</summary>
		public virtual IEntityRelation CartItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CartItems", true, new[] { ProductFields.Id, CartItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and OrderItemEntity over the 1:n relation they have, using the relation between the fields: Product.Id - OrderItem.ProductId</summary>
		public virtual IEntityRelation OrderItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderItems", true, new[] { ProductFields.Id, OrderItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductImageEntity over the 1:n relation they have, using the relation between the fields: Product.Id - ProductImage.ProductId</summary>
		public virtual IEntityRelation ProductImageEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductImages", true, new[] { ProductFields.Id, ProductImageFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ReviewEntity over the 1:n relation they have, using the relation between the fields: Product.Id - Review.ProductId</summary>
		public virtual IEntityRelation ReviewEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Reviews", true, new[] { ProductFields.Id, ReviewFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and WishlistItemEntity over the 1:n relation they have, using the relation between the fields: Product.Id - WishlistItem.ProductId</summary>
		public virtual IEntityRelation WishlistItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WishlistItems", true, new[] { ProductFields.Id, WishlistItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and CategoryEntity over the m:1 relation they have, using the relation between the fields: Product.CategoryId - Category.Id</summary>
		public virtual IEntityRelation CategoryEntityUsingCategoryId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Category", false, new[] { CategoryFields.Id, ProductFields.CategoryId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductRelations
	{
		internal static readonly IEntityRelation CartItemEntityUsingProductIdStatic = new ProductRelations().CartItemEntityUsingProductId;
		internal static readonly IEntityRelation OrderItemEntityUsingProductIdStatic = new ProductRelations().OrderItemEntityUsingProductId;
		internal static readonly IEntityRelation ProductImageEntityUsingProductIdStatic = new ProductRelations().ProductImageEntityUsingProductId;
		internal static readonly IEntityRelation ReviewEntityUsingProductIdStatic = new ProductRelations().ReviewEntityUsingProductId;
		internal static readonly IEntityRelation WishlistItemEntityUsingProductIdStatic = new ProductRelations().WishlistItemEntityUsingProductId;
		internal static readonly IEntityRelation CategoryEntityUsingCategoryIdStatic = new ProductRelations().CategoryEntityUsingCategoryId;

		/// <summary>CTor</summary>
		static StaticProductRelations() { }
	}
}
