//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ECommerce.Data.HelperClasses;
using ECommerce.Data.FactoryClasses;
using ECommerce.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ECommerce.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'WishlistItem'.<br/><br/></summary>
	[Serializable]
	public partial class WishlistItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private ProductEntity _product;
		private WishlistEntity _wishlist;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static WishlistItemEntityStaticMetaData _staticMetaData = new WishlistItemEntityStaticMetaData();
		private static WishlistItemRelations _relationsFactory = new WishlistItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
			/// <summary>Member name Wishlist</summary>
			public static readonly string Wishlist = "Wishlist";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class WishlistItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public WishlistItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("WishlistItemEntity", InheritanceHierarchyType.None, false, (int)ECommerce.Data.EntityType.WishlistItemEntity, typeof(WishlistItemEntity), typeof(WishlistItemEntityFactory), false);
				AddNavigatorMetaData<WishlistItemEntity, ProductEntity>("Product", "WishlistItems", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, ECommerce.Data.RelationClasses.StaticWishlistItemRelations.ProductEntityUsingProductIdStatic, ()=>new WishlistItemRelations().ProductEntityUsingProductId, null, new int[] { (int)WishlistItemFieldIndex.ProductId }, null, true, (int)ECommerce.Data.EntityType.ProductEntity);
				AddNavigatorMetaData<WishlistItemEntity, WishlistEntity>("Wishlist", "WishlistItems", (a, b) => a._wishlist = b, a => a._wishlist, (a, b) => a.Wishlist = b, ECommerce.Data.RelationClasses.StaticWishlistItemRelations.WishlistEntityUsingWishlistIdStatic, ()=>new WishlistItemRelations().WishlistEntityUsingWishlistId, null, new int[] { (int)WishlistItemFieldIndex.WishlistId }, null, true, (int)ECommerce.Data.EntityType.WishlistEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static WishlistItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public WishlistItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public WishlistItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this WishlistItemEntity</param>
		public WishlistItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WishlistItem which data should be fetched into this WishlistItem object</param>
		public WishlistItemEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WishlistItem which data should be fetched into this WishlistItem object</param>
		/// <param name="validator">The custom validator object for this WishlistItemEntity</param>
		public WishlistItemEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected WishlistItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: ProductId , WishlistId .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCProductIdWishlistId()
		{
			var filter = new PredicateExpression();
			filter.Add(ECommerce.Data.HelperClasses.WishlistItemFields.ProductId == this.Fields.GetCurrentValue((int)WishlistItemFieldIndex.ProductId));
			filter.Add(ECommerce.Data.HelperClasses.WishlistItemFields.WishlistId == this.Fields.GetCurrentValue((int)WishlistItemFieldIndex.WishlistId));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Wishlist' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWishlist() { return CreateRelationInfoForNavigator("Wishlist"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this WishlistItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static WishlistItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Wishlist' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWishlist { get { return _staticMetaData.GetPrefetchPathElement("Wishlist", CommonEntityBase.CreateEntityCollection<WishlistEntity>()); } }

		/// <summary>The AddedAt property of the Entity WishlistItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlist_items"."added_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime AddedAt
		{
			get { return (System.DateTime)GetValue((int)WishlistItemFieldIndex.AddedAt, true); }
			set { SetValue((int)WishlistItemFieldIndex.AddedAt, value); }
		}

		/// <summary>The Id property of the Entity WishlistItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlist_items"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)WishlistItemFieldIndex.Id, true); }
			set { SetValue((int)WishlistItemFieldIndex.Id, value); }
		}

		/// <summary>The Notes property of the Entity WishlistItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlist_items"."notes".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Notes
		{
			get { return (System.String)GetValue((int)WishlistItemFieldIndex.Notes, true); }
			set { SetValue((int)WishlistItemFieldIndex.Notes, value); }
		}

		/// <summary>The ProductId property of the Entity WishlistItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlist_items"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)WishlistItemFieldIndex.ProductId, true); }
			set { SetValue((int)WishlistItemFieldIndex.ProductId, value); }
		}

		/// <summary>The WishlistId property of the Entity WishlistItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlist_items"."wishlist_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid WishlistId
		{
			get { return (System.Guid)GetValue((int)WishlistItemFieldIndex.WishlistId, true); }
			set { SetValue((int)WishlistItemFieldIndex.WishlistId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}

		/// <summary>Gets / sets related entity of type 'WishlistEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual WishlistEntity Wishlist
		{
			get { return _wishlist; }
			set { SetSingleRelatedEntityNavigator(value, "Wishlist"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ECommerce.Data
{
	public enum WishlistItemFieldIndex
	{
		///<summary>AddedAt. </summary>
		AddedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Notes. </summary>
		Notes,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>WishlistId. </summary>
		WishlistId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ECommerce.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: WishlistItem. </summary>
	public partial class WishlistItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between WishlistItemEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: WishlistItem.ProductId - Product.Id</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.Id, WishlistItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between WishlistItemEntity and WishlistEntity over the m:1 relation they have, using the relation between the fields: WishlistItem.WishlistId - Wishlist.Id</summary>
		public virtual IEntityRelation WishlistEntityUsingWishlistId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Wishlist", false, new[] { WishlistFields.Id, WishlistItemFields.WishlistId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticWishlistItemRelations
	{
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new WishlistItemRelations().ProductEntityUsingProductId;
		internal static readonly IEntityRelation WishlistEntityUsingWishlistIdStatic = new WishlistItemRelations().WishlistEntityUsingWishlistId;

		/// <summary>CTor</summary>
		static StaticWishlistItemRelations() { }
	}
}
