//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitAddressEntityMappings();
			InitCartEntityMappings();
			InitCartItemEntityMappings();
			InitCartSummaryViewEntityMappings();
			InitCategoryEntityMappings();
			InitCategoryPerformanceViewEntityMappings();
			InitCouponEntityMappings();
			InitCouponUsageEntityMappings();
			InitCustomerOrdersViewEntityMappings();
			InitOrderEntityMappings();
			InitOrderItemEntityMappings();
			InitOrderSummaryViewEntityMappings();
			InitPaymentEntityMappings();
			InitProductEntityMappings();
			InitProductImageEntityMappings();
			InitProductInventoryViewEntityMappings();
			InitProductRatingViewEntityMappings();
			InitReviewEntityMappings();
			InitSalesPerformanceViewEntityMappings();
			InitSavedPaymentMethodEntityMappings();
			InitUserEntityMappings();
			InitWishlistEntityMappings();
			InitWishlistItemEntityMappings();
		}

		/// <summary>Inits AddressEntity's mappings</summary>
		private void InitAddressEntityMappings()
		{
			this.AddElementMapping("AddressEntity", @"ecommerce", @"public", "addresses", 14, 0);
			this.AddElementFieldMapping("AddressEntity", "AddressLine1", "address_line1", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AddressEntity", "AddressLine2", "address_line2", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AddressEntity", "AddressType", "address_type", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AddressEntity", "City", "city", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("AddressEntity", "Country", "country", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("AddressEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("AddressEntity", "FullName", "full_name", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("AddressEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 7);
			this.AddElementFieldMapping("AddressEntity", "IsDefault", "is_default", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 8);
			this.AddElementFieldMapping("AddressEntity", "PhoneNumber", "phone_number", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("AddressEntity", "PostalCode", "postal_code", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("AddressEntity", "State", "state", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("AddressEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 12);
			this.AddElementFieldMapping("AddressEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 13);
		}

		/// <summary>Inits CartEntity's mappings</summary>
		private void InitCartEntityMappings()
		{
			this.AddElementMapping("CartEntity", @"ecommerce", @"public", "carts", 11, 0);
			this.AddElementFieldMapping("CartEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("CartEntity", "Discount", "discount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 1);
			this.AddElementFieldMapping("CartEntity", "DiscountCode", "discount_code", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CartEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("CartEntity", "SessionId", "session_id", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CartEntity", "Shipping", "shipping", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 5);
			this.AddElementFieldMapping("CartEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("CartEntity", "Tax", "tax", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 7);
			this.AddElementFieldMapping("CartEntity", "Total", "total", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 8);
			this.AddElementFieldMapping("CartEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 9);
			this.AddElementFieldMapping("CartEntity", "UserId", "user_id", true, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 10);
		}

		/// <summary>Inits CartItemEntity's mappings</summary>
		private void InitCartItemEntityMappings()
		{
			this.AddElementMapping("CartItemEntity", @"ecommerce", @"public", "cart_items", 8, 0);
			this.AddElementFieldMapping("CartItemEntity", "CartId", "cart_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("CartItemEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("CartItemEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("CartItemEntity", "Price", "price", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 3);
			this.AddElementFieldMapping("CartItemEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("CartItemEntity", "Quantity", "quantity", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("CartItemEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("CartItemEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
		}

		/// <summary>Inits CartSummaryViewEntity's mappings</summary>
		private void InitCartSummaryViewEntityMappings()
		{
			this.AddElementMapping("CartSummaryViewEntity", @"ecommerce", @"public", "cart_summary_view", 15, 4);
			this.AddElementFieldMapping("CartSummaryViewEntity", "CartId", "cart_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("CartSummaryViewEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("CartSummaryViewEntity", "Discount", "discount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 2);
			this.AddElementFieldMapping("CartSummaryViewEntity", "DiscountCode", "discount_code", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("CartSummaryViewEntity", "HoursSinceUpdate", "hours_since_update", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 4);
			this.AddElementFieldMapping("CartSummaryViewEntity", "SessionId", "session_id", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CartSummaryViewEntity", "Shipping", "shipping", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("CartSummaryViewEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 7);
			this.AddElementFieldMapping("CartSummaryViewEntity", "Tax", "tax", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 8);
			this.AddElementFieldMapping("CartSummaryViewEntity", "Total", "total", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 9);
			this.AddElementFieldMapping("CartSummaryViewEntity", "TotalItems", "total_items", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 10);
			this.AddElementFieldMapping("CartSummaryViewEntity", "TotalQuantity", "total_quantity", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 11);
			this.AddElementFieldMapping("CartSummaryViewEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 12);
			this.AddElementFieldMapping("CartSummaryViewEntity", "UserEmail", "user_email", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("CartSummaryViewEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 14);
		}

		/// <summary>Inits CategoryEntity's mappings</summary>
		private void InitCategoryEntityMappings()
		{
			this.AddElementMapping("CategoryEntity", @"ecommerce", @"public", "categories", 11, 0);
			this.AddElementFieldMapping("CategoryEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("CategoryEntity", "Description", "description", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("CategoryEntity", "DisplayOrder", "display_order", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("CategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("CategoryEntity", "ImageUrl", "image_url", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("CategoryEntity", "Level", "level", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 6);
			this.AddElementFieldMapping("CategoryEntity", "Name", "name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("CategoryEntity", "ParentCategoryId", "parent_category_id", true, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 8);
			this.AddElementFieldMapping("CategoryEntity", "Slug", "slug", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("CategoryEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 10);
		}

		/// <summary>Inits CategoryPerformanceViewEntity's mappings</summary>
		private void InitCategoryPerformanceViewEntityMappings()
		{
			this.AddElementMapping("CategoryPerformanceViewEntity", @"ecommerce", @"public", "category_performance_view", 11, 4);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "ActiveProducts", "active_products", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "AverageCategoryRating", "average_category_rating", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 1);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "AvgPrice", "avg_price", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 2);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "CategoryId", "category_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "CategoryName", "category_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "CategorySlug", "category_slug", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "MaxPrice", "max_price", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "MinPrice", "min_price", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 7);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "TotalProducts", "total_products", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 8);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "TotalSales", "total_sales", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 9);
			this.AddElementFieldMapping("CategoryPerformanceViewEntity", "TotalStock", "total_stock", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 10);
		}

		/// <summary>Inits CouponEntity's mappings</summary>
		private void InitCouponEntityMappings()
		{
			this.AddElementMapping("CouponEntity", @"ecommerce", @"public", "coupons", 17, 0);
			this.AddElementFieldMapping("CouponEntity", "AppliesToCategories", "applies_to_categories", true, "Array", 2147483647, 0, 0, false, "", null, typeof(System.String[]), 0);
			this.AddElementFieldMapping("CouponEntity", "AppliesToProducts", "applies_to_products", true, "Array", 2147483647, 0, 0, false, "", null, typeof(System.String[]), 1);
			this.AddElementFieldMapping("CouponEntity", "Code", "code", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CouponEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("CouponEntity", "Description", "description", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CouponEntity", "DiscountType", "discount_type", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CouponEntity", "DiscountValue", "discount_value", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("CouponEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 7);
			this.AddElementFieldMapping("CouponEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 8);
			this.AddElementFieldMapping("CouponEntity", "MaxDiscountAmount", "max_discount_amount", true, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 9);
			this.AddElementFieldMapping("CouponEntity", "MaxUses", "max_uses", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 10);
			this.AddElementFieldMapping("CouponEntity", "MaxUsesPerUser", "max_uses_per_user", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 11);
			this.AddElementFieldMapping("CouponEntity", "MinOrderAmount", "min_order_amount", true, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 12);
			this.AddElementFieldMapping("CouponEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 13);
			this.AddElementFieldMapping("CouponEntity", "UsedCount", "used_count", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 14);
			this.AddElementFieldMapping("CouponEntity", "ValidFrom", "valid_from", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 15);
			this.AddElementFieldMapping("CouponEntity", "ValidUntil", "valid_until", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 16);
		}

		/// <summary>Inits CouponUsageEntity's mappings</summary>
		private void InitCouponUsageEntityMappings()
		{
			this.AddElementMapping("CouponUsageEntity", @"ecommerce", @"public", "coupon_usages", 6, 0);
			this.AddElementFieldMapping("CouponUsageEntity", "CouponId", "coupon_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("CouponUsageEntity", "DiscountAmount", "discount_amount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 1);
			this.AddElementFieldMapping("CouponUsageEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("CouponUsageEntity", "OrderId", "order_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("CouponUsageEntity", "UsedAt", "used_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("CouponUsageEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
		}

		/// <summary>Inits CustomerOrdersViewEntity's mappings</summary>
		private void InitCustomerOrdersViewEntityMappings()
		{
			this.AddElementMapping("CustomerOrdersViewEntity", @"ecommerce", @"public", "customer_orders_view", 12, 4);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "AverageOrderValue", "average_order_value", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "CancelledOrders", "cancelled_orders", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "CustomerSince", "customer_since", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "DeliveredOrders", "delivered_orders", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 3);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "Email", "email", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "FirstName", "first_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "FirstOrderDate", "first_order_date", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "LastName", "last_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "LastOrderDate", "last_order_date", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 8);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "LifetimeValue", "lifetime_value", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 9);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "TotalOrders", "total_orders", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 10);
			this.AddElementFieldMapping("CustomerOrdersViewEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 11);
		}

		/// <summary>Inits OrderEntity's mappings</summary>
		private void InitOrderEntityMappings()
		{
			this.AddElementMapping("OrderEntity", @"ecommerce", @"public", "orders", 40, 0);
			this.AddElementFieldMapping("OrderEntity", "BillingAddressLine1", "billing_address_line1", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("OrderEntity", "BillingAddressLine2", "billing_address_line2", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("OrderEntity", "BillingCity", "billing_city", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("OrderEntity", "BillingCountry", "billing_country", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("OrderEntity", "BillingFullName", "billing_full_name", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("OrderEntity", "BillingPhone", "billing_phone", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("OrderEntity", "BillingPostalCode", "billing_postal_code", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("OrderEntity", "BillingState", "billing_state", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("OrderEntity", "CancellationReason", "cancellation_reason", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("OrderEntity", "CancelledAt", "cancelled_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 9);
			this.AddElementFieldMapping("OrderEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 10);
			this.AddElementFieldMapping("OrderEntity", "Currency", "currency", false, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("OrderEntity", "DeliveredAt", "delivered_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 12);
			this.AddElementFieldMapping("OrderEntity", "Discount", "discount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 13);
			this.AddElementFieldMapping("OrderEntity", "DiscountCode", "discount_code", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("OrderEntity", "EstimatedDeliveryDate", "estimated_delivery_date", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 15);
			this.AddElementFieldMapping("OrderEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 16);
			this.AddElementFieldMapping("OrderEntity", "Notes", "notes", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 17);
			this.AddElementFieldMapping("OrderEntity", "OrderNumber", "order_number", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 18);
			this.AddElementFieldMapping("OrderEntity", "PaymentMethod", "payment_method", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("OrderEntity", "PaymentStatus", "payment_status", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 20);
			this.AddElementFieldMapping("OrderEntity", "PaymentTransactionId", "payment_transaction_id", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 21);
			this.AddElementFieldMapping("OrderEntity", "ShippingAddressLine1", "shipping_address_line1", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("OrderEntity", "ShippingAddressLine2", "shipping_address_line2", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 23);
			this.AddElementFieldMapping("OrderEntity", "ShippingCarrier", "shipping_carrier", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 24);
			this.AddElementFieldMapping("OrderEntity", "ShippingCity", "shipping_city", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 25);
			this.AddElementFieldMapping("OrderEntity", "ShippingCost", "shipping_cost", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 26);
			this.AddElementFieldMapping("OrderEntity", "ShippingCountry", "shipping_country", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 27);
			this.AddElementFieldMapping("OrderEntity", "ShippingFullName", "shipping_full_name", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 28);
			this.AddElementFieldMapping("OrderEntity", "ShippingMethod", "shipping_method", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 29);
			this.AddElementFieldMapping("OrderEntity", "ShippingPhone", "shipping_phone", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 30);
			this.AddElementFieldMapping("OrderEntity", "ShippingPostalCode", "shipping_postal_code", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 31);
			this.AddElementFieldMapping("OrderEntity", "ShippingState", "shipping_state", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 32);
			this.AddElementFieldMapping("OrderEntity", "Status", "status", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 33);
			this.AddElementFieldMapping("OrderEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 34);
			this.AddElementFieldMapping("OrderEntity", "Tax", "tax", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 35);
			this.AddElementFieldMapping("OrderEntity", "Total", "total", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 36);
			this.AddElementFieldMapping("OrderEntity", "TrackingNumber", "tracking_number", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 37);
			this.AddElementFieldMapping("OrderEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 38);
			this.AddElementFieldMapping("OrderEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 39);
		}

		/// <summary>Inits OrderItemEntity's mappings</summary>
		private void InitOrderItemEntityMappings()
		{
			this.AddElementMapping("OrderItemEntity", @"ecommerce", @"public", "order_items", 10, 0);
			this.AddElementFieldMapping("OrderItemEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("OrderItemEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("OrderItemEntity", "OrderId", "order_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("OrderItemEntity", "Price", "price", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 3);
			this.AddElementFieldMapping("OrderItemEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("OrderItemEntity", "ProductImageUrl", "product_image_url", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("OrderItemEntity", "ProductName", "product_name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("OrderItemEntity", "ProductSku", "product_sku", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("OrderItemEntity", "Quantity", "quantity", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("OrderItemEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 9);
		}

		/// <summary>Inits OrderSummaryViewEntity's mappings</summary>
		private void InitOrderSummaryViewEntityMappings()
		{
			this.AddElementMapping("OrderSummaryViewEntity", @"ecommerce", @"public", "order_summary_view", 26, 4);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Currency", "currency", false, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "CustomerName", "customer_name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "DeliveredAt", "delivered_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Discount", "discount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 4);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "EstimatedDeliveryDate", "estimated_delivery_date", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 6);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "OrderNumber", "order_number", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "PaymentMethod", "payment_method", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "PaymentStatus", "payment_status", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingCarrier", "shipping_carrier", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingCity", "shipping_city", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingCost", "shipping_cost", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 12);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingCountry", "shipping_country", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingFullName", "shipping_full_name", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "ShippingState", "shipping_state", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Status", "status", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 16);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Subtotal", "subtotal", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 17);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Tax", "tax", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 18);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "Total", "total", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 19);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "TotalItems", "total_items", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 20);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "TotalQuantity", "total_quantity", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 21);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "TrackingNumber", "tracking_number", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 23);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "UserEmail", "user_email", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 24);
			this.AddElementFieldMapping("OrderSummaryViewEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 25);
		}

		/// <summary>Inits PaymentEntity's mappings</summary>
		private void InitPaymentEntityMappings()
		{
			this.AddElementMapping("PaymentEntity", @"ecommerce", @"public", "payments", 18, 0);
			this.AddElementFieldMapping("PaymentEntity", "Amount", "amount", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("PaymentEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("PaymentEntity", "Currency", "currency", false, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("PaymentEntity", "FailureReason", "failure_reason", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("PaymentEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("PaymentEntity", "OrderId", "order_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
			this.AddElementFieldMapping("PaymentEntity", "PaidAt", "paid_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("PaymentEntity", "PaymentMethod", "payment_method", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("PaymentEntity", "PaymentProvider", "payment_provider", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("PaymentEntity", "PaypalOrderId", "paypal_order_id", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("PaymentEntity", "RefundAmount", "refund_amount", true, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 10);
			this.AddElementFieldMapping("PaymentEntity", "RefundedAt", "refunded_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 11);
			this.AddElementFieldMapping("PaymentEntity", "RefundReason", "refund_reason", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("PaymentEntity", "Status", "status", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("PaymentEntity", "StripePaymentIntentId", "stripe_payment_intent_id", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("PaymentEntity", "TransactionId", "transaction_id", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("PaymentEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 16);
			this.AddElementFieldMapping("PaymentEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 17);
		}

		/// <summary>Inits ProductEntity's mappings</summary>
		private void InitProductEntityMappings()
		{
			this.AddElementMapping("ProductEntity", @"ecommerce", @"public", "products", 26, 0);
			this.AddElementFieldMapping("ProductEntity", "AverageRating", "average_rating", false, "Numeric", 0, 3, 2, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("ProductEntity", "Brand", "brand", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ProductEntity", "CategoryId", "category_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("ProductEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("ProductEntity", "Currency", "currency", false, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("ProductEntity", "Description", "description", true, "Varchar", 5000, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("ProductEntity", "Dimensions", "dimensions", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("ProductEntity", "DiscountPercentage", "discount_percentage", true, "Numeric", 0, 5, 2, false, "", null, typeof(System.Decimal), 7);
			this.AddElementFieldMapping("ProductEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 8);
			this.AddElementFieldMapping("ProductEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 9);
			this.AddElementFieldMapping("ProductEntity", "IsFeatured", "is_featured", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 10);
			this.AddElementFieldMapping("ProductEntity", "LowStockThreshold", "low_stock_threshold", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 11);
			this.AddElementFieldMapping("ProductEntity", "MetaDescription", "meta_description", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("ProductEntity", "MetaKeywords", "meta_keywords", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("ProductEntity", "MetaTitle", "meta_title", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("ProductEntity", "Name", "name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("ProductEntity", "OriginalPrice", "original_price", true, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 16);
			this.AddElementFieldMapping("ProductEntity", "Price", "price", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 17);
			this.AddElementFieldMapping("ProductEntity", "ShortDescription", "short_description", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 18);
			this.AddElementFieldMapping("ProductEntity", "Sku", "sku", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("ProductEntity", "Slug", "slug", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 20);
			this.AddElementFieldMapping("ProductEntity", "StockQuantity", "stock_quantity", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 21);
			this.AddElementFieldMapping("ProductEntity", "TotalReviews", "total_reviews", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 22);
			this.AddElementFieldMapping("ProductEntity", "TotalSales", "total_sales", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 23);
			this.AddElementFieldMapping("ProductEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 24);
			this.AddElementFieldMapping("ProductEntity", "Weight", "weight", true, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 25);
		}

		/// <summary>Inits ProductImageEntity's mappings</summary>
		private void InitProductImageEntityMappings()
		{
			this.AddElementMapping("ProductImageEntity", @"ecommerce", @"public", "product_images", 7, 0);
			this.AddElementFieldMapping("ProductImageEntity", "AltText", "alt_text", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ProductImageEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("ProductImageEntity", "DisplayOrder", "display_order", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("ProductImageEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("ProductImageEntity", "ImageUrl", "image_url", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("ProductImageEntity", "IsPrimary", "is_primary", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("ProductImageEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 6);
		}

		/// <summary>Inits ProductInventoryViewEntity's mappings</summary>
		private void InitProductInventoryViewEntityMappings()
		{
			this.AddElementMapping("ProductInventoryViewEntity", @"ecommerce", @"public", "product_inventory_view", 18, 4);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "AverageRating", "average_rating", false, "Numeric", 0, 3, 2, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "CategoryName", "category_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "CategorySlug", "category_slug", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "DiscountPercentage", "discount_percentage", false, "Numeric", 0, 5, 2, false, "", null, typeof(System.Decimal), 4);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 6);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "IsFeatured", "is_featured", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 7);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "LowStockThreshold", "low_stock_threshold", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "Name", "name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "OriginalPrice", "original_price", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 10);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "Price", "price", false, "Numeric", 0, 10, 2, false, "", null, typeof(System.Decimal), 11);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "Sku", "sku", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "StockQuantity", "stock_quantity", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 13);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "StockStatus", "stock_status", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "TotalReviews", "total_reviews", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 15);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "TotalSales", "total_sales", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 16);
			this.AddElementFieldMapping("ProductInventoryViewEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 17);
		}

		/// <summary>Inits ProductRatingViewEntity's mappings</summary>
		private void InitProductRatingViewEntityMappings()
		{
			this.AddElementMapping("ProductRatingViewEntity", @"ecommerce", @"public", "product_rating_view", 11, 4);
			this.AddElementFieldMapping("ProductRatingViewEntity", "AverageRating", "average_rating", false, "Numeric", 0, 3, 2, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("ProductRatingViewEntity", "CalculatedAvgRating", "calculated_avg_rating", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 1);
			this.AddElementFieldMapping("ProductRatingViewEntity", "FiveStarCount", "five_star_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 2);
			this.AddElementFieldMapping("ProductRatingViewEntity", "FourStarCount", "four_star_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 3);
			this.AddElementFieldMapping("ProductRatingViewEntity", "OneStarCount", "one_star_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("ProductRatingViewEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
			this.AddElementFieldMapping("ProductRatingViewEntity", "ProductName", "product_name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("ProductRatingViewEntity", "ThreeStarCount", "three_star_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 7);
			this.AddElementFieldMapping("ProductRatingViewEntity", "TotalReviews", "total_reviews", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("ProductRatingViewEntity", "TwoStarCount", "two_star_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 9);
			this.AddElementFieldMapping("ProductRatingViewEntity", "VerifiedPurchaseCount", "verified_purchase_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 10);
		}

		/// <summary>Inits ReviewEntity's mappings</summary>
		private void InitReviewEntityMappings()
		{
			this.AddElementMapping("ReviewEntity", @"ecommerce", @"public", "reviews", 13, 0);
			this.AddElementFieldMapping("ReviewEntity", "Comment", "comment", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ReviewEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("ReviewEntity", "HelpfulCount", "helpful_count", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("ReviewEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("ReviewEntity", "IsApproved", "is_approved", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 4);
			this.AddElementFieldMapping("ReviewEntity", "IsVerifiedPurchase", "is_verified_purchase", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("ReviewEntity", "OrderId", "order_id", true, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 6);
			this.AddElementFieldMapping("ReviewEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 7);
			this.AddElementFieldMapping("ReviewEntity", "Rating", "rating", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("ReviewEntity", "Title", "title", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("ReviewEntity", "UnhelpfulCount", "unhelpful_count", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 10);
			this.AddElementFieldMapping("ReviewEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 11);
			this.AddElementFieldMapping("ReviewEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 12);
		}

		/// <summary>Inits SalesPerformanceViewEntity's mappings</summary>
		private void InitSalesPerformanceViewEntityMappings()
		{
			this.AddElementMapping("SalesPerformanceViewEntity", @"ecommerce", @"public", "sales_performance_view", 10, 4);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "AverageOrderValue", "average_order_value", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 0);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "OrdersCount", "orders_count", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "SaleDate", "sale_date", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalDiscounts", "total_discounts", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 3);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalItemsSold", "total_items_sold", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalRevenue", "total_revenue", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 5);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalShipping", "total_shipping", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 6);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalSubtotal", "total_subtotal", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 7);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "TotalTax", "total_tax", false, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 8);
			this.AddElementFieldMapping("SalesPerformanceViewEntity", "UniqueCustomers", "unique_customers", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 9);
		}

		/// <summary>Inits SavedPaymentMethodEntity's mappings</summary>
		private void InitSavedPaymentMethodEntityMappings()
		{
			this.AddElementMapping("SavedPaymentMethodEntity", @"ecommerce", @"public", "saved_payment_methods", 18, 0);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingAddressLine1", "billing_address_line1", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingCity", "billing_city", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingCountry", "billing_country", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingName", "billing_name", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingPostalCode", "billing_postal_code", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "BillingState", "billing_state", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "CardBrand", "card_brand", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "CardExpMonth", "card_exp_month", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "CardExpYear", "card_exp_year", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "CardLastFour", "card_last_four", true, "Varchar", 4, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 10);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 11);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "IsDefault", "is_default", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 12);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "PaymentMethodType", "payment_method_type", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "PaymentProvider", "payment_provider", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "StripePaymentMethodId", "stripe_payment_method_id", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 16);
			this.AddElementFieldMapping("SavedPaymentMethodEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 17);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"ecommerce", @"public", "users", 17, 0);
			this.AddElementFieldMapping("UserEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("UserEntity", "Email", "email", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "EmailVerificationToken", "email_verification_token", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "FailedLoginAttempts", "failed_login_attempts", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("UserEntity", "FirstName", "first_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
			this.AddElementFieldMapping("UserEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 6);
			this.AddElementFieldMapping("UserEntity", "IsEmailVerified", "is_email_verified", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 7);
			this.AddElementFieldMapping("UserEntity", "LastLoginAt", "last_login_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 8);
			this.AddElementFieldMapping("UserEntity", "LastName", "last_name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("UserEntity", "LockoutEnd", "lockout_end", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 10);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "password_hash", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("UserEntity", "PasswordResetExpires", "password_reset_expires", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 12);
			this.AddElementFieldMapping("UserEntity", "PasswordResetToken", "password_reset_token", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("UserEntity", "PhoneNumber", "phone_number", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("UserEntity", "Role", "role", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("UserEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 16);
		}

		/// <summary>Inits WishlistEntity's mappings</summary>
		private void InitWishlistEntityMappings()
		{
			this.AddElementMapping("WishlistEntity", @"ecommerce", @"public", "wishlists", 7, 0);
			this.AddElementFieldMapping("WishlistEntity", "CreatedAt", "created_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("WishlistEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("WishlistEntity", "IsDefault", "is_default", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("WishlistEntity", "IsPublic", "is_public", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 3);
			this.AddElementFieldMapping("WishlistEntity", "Name", "name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("WishlistEntity", "UpdatedAt", "updated_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("WishlistEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 6);
		}

		/// <summary>Inits WishlistItemEntity's mappings</summary>
		private void InitWishlistItemEntityMappings()
		{
			this.AddElementMapping("WishlistItemEntity", @"ecommerce", @"public", "wishlist_items", 5, 0);
			this.AddElementFieldMapping("WishlistItemEntity", "AddedAt", "added_at", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("WishlistItemEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("WishlistItemEntity", "Notes", "notes", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("WishlistItemEntity", "ProductId", "product_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("WishlistItemEntity", "WishlistId", "wishlist_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
		}

	}
}
