//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'CartSummaryView'.<br/><br/></summary>
	[Serializable]
	public partial class CartSummaryViewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CartSummaryViewEntityStaticMetaData _staticMetaData = new CartSummaryViewEntityStaticMetaData();
		private static CartSummaryViewRelations _relationsFactory = new CartSummaryViewRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CartSummaryViewEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CartSummaryViewEntityStaticMetaData()
			{
				SetEntityCoreInfo("CartSummaryViewEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.CartSummaryViewEntity, typeof(CartSummaryViewEntity), typeof(CartSummaryViewEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static CartSummaryViewEntity()
		{
		}

		/// <summary> CTor</summary>
		public CartSummaryViewEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CartSummaryViewEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CartSummaryViewEntity</param>
		public CartSummaryViewEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CartSummaryViewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CartSummaryViewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CartSummaryViewRelations Relations { get { return _relationsFactory; } }

		/// <summary>The CartId property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."cart_id".<br/>View field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CartId
		{
			get { return (System.Guid)GetValue((int)CartSummaryViewFieldIndex.CartId, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.CartId, value); }
		}

		/// <summary>The CreatedAt property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."created_at".<br/>View field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)CartSummaryViewFieldIndex.CreatedAt, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Discount property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."discount".<br/>View field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Discount
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.Discount, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.Discount, value); }
		}

		/// <summary>The DiscountCode property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."discount_code".<br/>View field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DiscountCode
		{
			get { return (System.String)GetValue((int)CartSummaryViewFieldIndex.DiscountCode, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.DiscountCode, value); }
		}

		/// <summary>The HoursSinceUpdate property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."hours_since_update".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal HoursSinceUpdate
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.HoursSinceUpdate, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.HoursSinceUpdate, value); }
		}

		/// <summary>The SessionId property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."session_id".<br/>View field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String SessionId
		{
			get { return (System.String)GetValue((int)CartSummaryViewFieldIndex.SessionId, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.SessionId, value); }
		}

		/// <summary>The Shipping property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."shipping".<br/>View field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Shipping
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.Shipping, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.Shipping, value); }
		}

		/// <summary>The Subtotal property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."subtotal".<br/>View field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Subtotal
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.Subtotal, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.Subtotal, value); }
		}

		/// <summary>The Tax property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."tax".<br/>View field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Tax
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.Tax, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.Tax, value); }
		}

		/// <summary>The Total property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."total".<br/>View field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Total
		{
			get { return (System.Decimal)GetValue((int)CartSummaryViewFieldIndex.Total, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.Total, value); }
		}

		/// <summary>The TotalItems property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."total_items".<br/>View field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 TotalItems
		{
			get { return (System.Int64)GetValue((int)CartSummaryViewFieldIndex.TotalItems, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.TotalItems, value); }
		}

		/// <summary>The TotalQuantity property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."total_quantity".<br/>View field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 TotalQuantity
		{
			get { return (System.Int64)GetValue((int)CartSummaryViewFieldIndex.TotalQuantity, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.TotalQuantity, value); }
		}

		/// <summary>The UpdatedAt property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."updated_at".<br/>View field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)CartSummaryViewFieldIndex.UpdatedAt, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserEmail property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."user_email".<br/>View field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String UserEmail
		{
			get { return (System.String)GetValue((int)CartSummaryViewFieldIndex.UserEmail, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.UserEmail, value); }
		}

		/// <summary>The UserId property of the Entity CartSummaryView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "cart_summary_view"."user_id".<br/>View field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)CartSummaryViewFieldIndex.UserId, true); }
			set { SetValue((int)CartSummaryViewFieldIndex.UserId, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum CartSummaryViewFieldIndex
	{
		///<summary>CartId. </summary>
		CartId,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Discount. </summary>
		Discount,
		///<summary>DiscountCode. </summary>
		DiscountCode,
		///<summary>HoursSinceUpdate. </summary>
		HoursSinceUpdate,
		///<summary>SessionId. </summary>
		SessionId,
		///<summary>Shipping. </summary>
		Shipping,
		///<summary>Subtotal. </summary>
		Subtotal,
		///<summary>Tax. </summary>
		Tax,
		///<summary>Total. </summary>
		Total,
		///<summary>TotalItems. </summary>
		TotalItems,
		///<summary>TotalQuantity. </summary>
		TotalQuantity,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserEmail. </summary>
		UserEmail,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CartSummaryView. </summary>
	public partial class CartSummaryViewRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCartSummaryViewRelations
	{

		/// <summary>CTor</summary>
		static StaticCartSummaryViewRelations() { }
	}
}
