//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Coupon'.<br/><br/></summary>
	[Serializable]
	public partial class CouponEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<CouponUsageEntity> _couponUsages;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CouponEntityStaticMetaData _staticMetaData = new CouponEntityStaticMetaData();
		private static CouponRelations _relationsFactory = new CouponRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CouponUsages</summary>
			public static readonly string CouponUsages = "CouponUsages";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CouponEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CouponEntityStaticMetaData()
			{
				SetEntityCoreInfo("CouponEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.CouponEntity, typeof(CouponEntity), typeof(CouponEntityFactory), false);
				AddNavigatorMetaData<CouponEntity, EntityCollection<CouponUsageEntity>>("CouponUsages", a => a._couponUsages, (a, b) => a._couponUsages = b, a => a.CouponUsages, () => new CouponRelations().CouponUsageEntityUsingCouponId, typeof(CouponUsageEntity), (int)ecommerce.EntityType.CouponUsageEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CouponEntity()
		{
		}

		/// <summary> CTor</summary>
		public CouponEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CouponEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CouponEntity</param>
		public CouponEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Coupon which data should be fetched into this Coupon object</param>
		public CouponEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Coupon which data should be fetched into this Coupon object</param>
		/// <param name="validator">The custom validator object for this CouponEntity</param>
		public CouponEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CouponEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CouponUsage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCouponUsages() { return CreateRelationInfoForNavigator("CouponUsages"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CouponEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CouponRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CouponUsage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCouponUsages { get { return _staticMetaData.GetPrefetchPathElement("CouponUsages", CommonEntityBase.CreateEntityCollection<CouponUsageEntity>()); } }

		/// <summary>The AppliesToCategories property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."applies_to_categories".<br/>Table field type characteristics (type, precision, scale, length): Array, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String[] AppliesToCategories
		{
			get { return (System.String[])GetValue((int)CouponFieldIndex.AppliesToCategories, true); }
			set { SetValue((int)CouponFieldIndex.AppliesToCategories, value); }
		}

		/// <summary>The AppliesToProducts property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."applies_to_products".<br/>Table field type characteristics (type, precision, scale, length): Array, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String[] AppliesToProducts
		{
			get { return (System.String[])GetValue((int)CouponFieldIndex.AppliesToProducts, true); }
			set { SetValue((int)CouponFieldIndex.AppliesToProducts, value); }
		}

		/// <summary>The Code property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.Code, true); }
			set { SetValue((int)CouponFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.CreatedAt, true); }
			set { SetValue((int)CouponFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.Description, true); }
			set { SetValue((int)CouponFieldIndex.Description, value); }
		}

		/// <summary>The DiscountType property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."discount_type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DiscountType
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.DiscountType, true); }
			set { SetValue((int)CouponFieldIndex.DiscountType, value); }
		}

		/// <summary>The DiscountValue property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."discount_value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal DiscountValue
		{
			get { return (System.Decimal)GetValue((int)CouponFieldIndex.DiscountValue, true); }
			set { SetValue((int)CouponFieldIndex.DiscountValue, value); }
		}

		/// <summary>The Id property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)CouponFieldIndex.Id, true); }
			set { SetValue((int)CouponFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)CouponFieldIndex.IsActive, true); }
			set { SetValue((int)CouponFieldIndex.IsActive, value); }
		}

		/// <summary>The MaxDiscountAmount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."max_discount_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MaxDiscountAmount
		{
			get { return (Nullable<System.Decimal>)GetValue((int)CouponFieldIndex.MaxDiscountAmount, false); }
			set { SetValue((int)CouponFieldIndex.MaxDiscountAmount, value); }
		}

		/// <summary>The MaxUses property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."max_uses".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> MaxUses
		{
			get { return (Nullable<System.Int32>)GetValue((int)CouponFieldIndex.MaxUses, false); }
			set { SetValue((int)CouponFieldIndex.MaxUses, value); }
		}

		/// <summary>The MaxUsesPerUser property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."max_uses_per_user".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 MaxUsesPerUser
		{
			get { return (System.Int32)GetValue((int)CouponFieldIndex.MaxUsesPerUser, true); }
			set { SetValue((int)CouponFieldIndex.MaxUsesPerUser, value); }
		}

		/// <summary>The MinOrderAmount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."min_order_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MinOrderAmount
		{
			get { return (Nullable<System.Decimal>)GetValue((int)CouponFieldIndex.MinOrderAmount, false); }
			set { SetValue((int)CouponFieldIndex.MinOrderAmount, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.UpdatedAt, true); }
			set { SetValue((int)CouponFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UsedCount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."used_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UsedCount
		{
			get { return (System.Int32)GetValue((int)CouponFieldIndex.UsedCount, true); }
			set { SetValue((int)CouponFieldIndex.UsedCount, value); }
		}

		/// <summary>The ValidFrom property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."valid_from".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ValidFrom
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.ValidFrom, true); }
			set { SetValue((int)CouponFieldIndex.ValidFrom, value); }
		}

		/// <summary>The ValidUntil property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."valid_until".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ValidUntil
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.ValidUntil, true); }
			set { SetValue((int)CouponFieldIndex.ValidUntil, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CouponUsageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CouponUsageEntity))]
		public virtual EntityCollection<CouponUsageEntity> CouponUsages { get { return GetOrCreateEntityCollection<CouponUsageEntity, CouponUsageEntityFactory>("Coupon", true, false, ref _couponUsages); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum CouponFieldIndex
	{
		///<summary>AppliesToCategories. </summary>
		AppliesToCategories,
		///<summary>AppliesToProducts. </summary>
		AppliesToProducts,
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>DiscountType. </summary>
		DiscountType,
		///<summary>DiscountValue. </summary>
		DiscountValue,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>MaxDiscountAmount. </summary>
		MaxDiscountAmount,
		///<summary>MaxUses. </summary>
		MaxUses,
		///<summary>MaxUsesPerUser. </summary>
		MaxUsesPerUser,
		///<summary>MinOrderAmount. </summary>
		MinOrderAmount,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UsedCount. </summary>
		UsedCount,
		///<summary>ValidFrom. </summary>
		ValidFrom,
		///<summary>ValidUntil. </summary>
		ValidUntil,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Coupon. </summary>
	public partial class CouponRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CouponEntity and CouponUsageEntity over the 1:n relation they have, using the relation between the fields: Coupon.Id - CouponUsage.CouponId</summary>
		public virtual IEntityRelation CouponUsageEntityUsingCouponId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CouponUsages", true, new[] { CouponFields.Id, CouponUsageFields.CouponId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCouponRelations
	{
		internal static readonly IEntityRelation CouponUsageEntityUsingCouponIdStatic = new CouponRelations().CouponUsageEntityUsingCouponId;

		/// <summary>CTor</summary>
		static StaticCouponRelations() { }
	}
}
