//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'OrderItem'.<br/><br/></summary>
	[Serializable]
	public partial class OrderItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private OrderEntity _order;
		private ProductEntity _product;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OrderItemEntityStaticMetaData _staticMetaData = new OrderItemEntityStaticMetaData();
		private static OrderItemRelations _relationsFactory = new OrderItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderItemEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.OrderItemEntity, typeof(OrderItemEntity), typeof(OrderItemEntityFactory), false);
				AddNavigatorMetaData<OrderItemEntity, OrderEntity>("Order", "OrderItems", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, ecommerce.RelationClasses.StaticOrderItemRelations.OrderEntityUsingOrderIdStatic, ()=>new OrderItemRelations().OrderEntityUsingOrderId, null, new int[] { (int)OrderItemFieldIndex.OrderId }, null, true, (int)ecommerce.EntityType.OrderEntity);
				AddNavigatorMetaData<OrderItemEntity, ProductEntity>("Product", "OrderItems", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, ecommerce.RelationClasses.StaticOrderItemRelations.ProductEntityUsingProductIdStatic, ()=>new OrderItemRelations().ProductEntityUsingProductId, null, new int[] { (int)OrderItemFieldIndex.ProductId }, null, true, (int)ecommerce.EntityType.ProductEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		public OrderItemEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>The CreatedAt property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)OrderItemFieldIndex.CreatedAt, true); }
			set { SetValue((int)OrderItemFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.Id, true); }
			set { SetValue((int)OrderItemFieldIndex.Id, value); }
		}

		/// <summary>The OrderId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrderId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.OrderId, true); }
			set { SetValue((int)OrderItemFieldIndex.OrderId, value); }
		}

		/// <summary>The Price property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.Price, true); }
			set { SetValue((int)OrderItemFieldIndex.Price, value); }
		}

		/// <summary>The ProductId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.ProductId, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductId, value); }
		}

		/// <summary>The ProductImageUrl property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_image_url".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ProductImageUrl
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductImageUrl, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductImageUrl, value); }
		}

		/// <summary>The ProductName property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ProductName
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductName, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductName, value); }
		}

		/// <summary>The ProductSku property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_sku".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ProductSku
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductSku, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductSku, value); }
		}

		/// <summary>The Quantity property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Quantity
		{
			get { return (System.Int32)GetValue((int)OrderItemFieldIndex.Quantity, true); }
			set { SetValue((int)OrderItemFieldIndex.Quantity, value); }
		}

		/// <summary>The Subtotal property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."subtotal".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Subtotal
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.Subtotal, true); }
			set { SetValue((int)OrderItemFieldIndex.Subtotal, value); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum OrderItemFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>Price. </summary>
		Price,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>ProductImageUrl. </summary>
		ProductImageUrl,
		///<summary>ProductName. </summary>
		ProductName,
		///<summary>ProductSku. </summary>
		ProductSku,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>Subtotal. </summary>
		Subtotal,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrderItem. </summary>
	public partial class OrderItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: OrderItem.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, OrderItemFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: OrderItem.ProductId - Product.Id</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.Id, OrderItemFields.ProductId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderItemRelations
	{
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new OrderItemRelations().OrderEntityUsingOrderId;
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new OrderItemRelations().ProductEntityUsingProductId;

		/// <summary>CTor</summary>
		static StaticOrderItemRelations() { }
	}
}
