//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Review'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private OrderEntity _order;
		private ProductEntity _product;
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ReviewEntityStaticMetaData _staticMetaData = new ReviewEntityStaticMetaData();
		private static ReviewRelations _relationsFactory = new ReviewRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.ReviewEntity, typeof(ReviewEntity), typeof(ReviewEntityFactory), false);
				AddNavigatorMetaData<ReviewEntity, OrderEntity>("Order", "Reviews", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, ecommerce.RelationClasses.StaticReviewRelations.OrderEntityUsingOrderIdStatic, ()=>new ReviewRelations().OrderEntityUsingOrderId, null, new int[] { (int)ReviewFieldIndex.OrderId }, null, true, (int)ecommerce.EntityType.OrderEntity);
				AddNavigatorMetaData<ReviewEntity, ProductEntity>("Product", "Reviews", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, ecommerce.RelationClasses.StaticReviewRelations.ProductEntityUsingProductIdStatic, ()=>new ReviewRelations().ProductEntityUsingProductId, null, new int[] { (int)ReviewFieldIndex.ProductId }, null, true, (int)ecommerce.EntityType.ProductEntity);
				AddNavigatorMetaData<ReviewEntity, UserEntity>("User", "Reviews", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, ecommerce.RelationClasses.StaticReviewRelations.UserEntityUsingUserIdStatic, ()=>new ReviewRelations().UserEntityUsingUserId, null, new int[] { (int)ReviewFieldIndex.UserId }, null, true, (int)ecommerce.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewEntity</param>
		public ReviewEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Review which data should be fetched into this Review object</param>
		public ReviewEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Review which data should be fetched into this Review object</param>
		/// <param name="validator">The custom validator object for this ReviewEntity</param>
		public ReviewEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The Comment property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."comment".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Comment
		{
			get { return (System.String)GetValue((int)ReviewFieldIndex.Comment, true); }
			set { SetValue((int)ReviewFieldIndex.Comment, value); }
		}

		/// <summary>The CreatedAt property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewFieldIndex.CreatedAt, value); }
		}

		/// <summary>The HelpfulCount property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."helpful_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 HelpfulCount
		{
			get { return (System.Int32)GetValue((int)ReviewFieldIndex.HelpfulCount, true); }
			set { SetValue((int)ReviewFieldIndex.HelpfulCount, value); }
		}

		/// <summary>The Id property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.Id, true); }
			set { SetValue((int)ReviewFieldIndex.Id, value); }
		}

		/// <summary>The IsApproved property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."is_approved".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsApproved
		{
			get { return (System.Boolean)GetValue((int)ReviewFieldIndex.IsApproved, true); }
			set { SetValue((int)ReviewFieldIndex.IsApproved, value); }
		}

		/// <summary>The IsVerifiedPurchase property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."is_verified_purchase".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsVerifiedPurchase
		{
			get { return (System.Boolean)GetValue((int)ReviewFieldIndex.IsVerifiedPurchase, true); }
			set { SetValue((int)ReviewFieldIndex.IsVerifiedPurchase, value); }
		}

		/// <summary>The OrderId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OrderId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ReviewFieldIndex.OrderId, false); }
			set { SetValue((int)ReviewFieldIndex.OrderId, value); }
		}

		/// <summary>The ProductId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.ProductId, true); }
			set { SetValue((int)ReviewFieldIndex.ProductId, value); }
		}

		/// <summary>The Rating property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."rating".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Rating
		{
			get { return (System.Int32)GetValue((int)ReviewFieldIndex.Rating, true); }
			set { SetValue((int)ReviewFieldIndex.Rating, value); }
		}

		/// <summary>The Title property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."title".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Title
		{
			get { return (System.String)GetValue((int)ReviewFieldIndex.Title, true); }
			set { SetValue((int)ReviewFieldIndex.Title, value); }
		}

		/// <summary>The UnhelpfulCount property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."unhelpful_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UnhelpfulCount
		{
			get { return (System.Int32)GetValue((int)ReviewFieldIndex.UnhelpfulCount, true); }
			set { SetValue((int)ReviewFieldIndex.UnhelpfulCount, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewFieldIndex.UpdatedAt, true); }
			set { SetValue((int)ReviewFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.UserId, true); }
			set { SetValue((int)ReviewFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum ReviewFieldIndex
	{
		///<summary>Comment. </summary>
		Comment,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>HelpfulCount. </summary>
		HelpfulCount,
		///<summary>Id. </summary>
		Id,
		///<summary>IsApproved. </summary>
		IsApproved,
		///<summary>IsVerifiedPurchase. </summary>
		IsVerifiedPurchase,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>Rating. </summary>
		Rating,
		///<summary>Title. </summary>
		Title,
		///<summary>UnhelpfulCount. </summary>
		UnhelpfulCount,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Review. </summary>
	public partial class ReviewRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReviewEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: Review.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, ReviewFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ReviewEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: Review.ProductId - Product.Id</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.Id, ReviewFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ReviewEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Review.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, ReviewFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewRelations
	{
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new ReviewRelations().OrderEntityUsingOrderId;
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new ReviewRelations().ProductEntityUsingProductId;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new ReviewRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticReviewRelations() { }
	}
}
