//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'SalesPerformanceView'.<br/><br/></summary>
	[Serializable]
	public partial class SalesPerformanceViewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static SalesPerformanceViewEntityStaticMetaData _staticMetaData = new SalesPerformanceViewEntityStaticMetaData();
		private static SalesPerformanceViewRelations _relationsFactory = new SalesPerformanceViewRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SalesPerformanceViewEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SalesPerformanceViewEntityStaticMetaData()
			{
				SetEntityCoreInfo("SalesPerformanceViewEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.SalesPerformanceViewEntity, typeof(SalesPerformanceViewEntity), typeof(SalesPerformanceViewEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SalesPerformanceViewEntity()
		{
		}

		/// <summary> CTor</summary>
		public SalesPerformanceViewEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SalesPerformanceViewEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SalesPerformanceViewEntity</param>
		public SalesPerformanceViewEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SalesPerformanceViewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SalesPerformanceViewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SalesPerformanceViewRelations Relations { get { return _relationsFactory; } }

		/// <summary>The AverageOrderValue property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."average_order_value".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal AverageOrderValue
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.AverageOrderValue, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.AverageOrderValue, value); }
		}

		/// <summary>The OrdersCount property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."orders_count".<br/>View field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 OrdersCount
		{
			get { return (System.Int64)GetValue((int)SalesPerformanceViewFieldIndex.OrdersCount, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.OrdersCount, value); }
		}

		/// <summary>The SaleDate property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."sale_date".<br/>View field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime SaleDate
		{
			get { return (System.DateTime)GetValue((int)SalesPerformanceViewFieldIndex.SaleDate, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.SaleDate, value); }
		}

		/// <summary>The TotalDiscounts property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_discounts".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalDiscounts
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.TotalDiscounts, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalDiscounts, value); }
		}

		/// <summary>The TotalItemsSold property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_items_sold".<br/>View field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 TotalItemsSold
		{
			get { return (System.Int64)GetValue((int)SalesPerformanceViewFieldIndex.TotalItemsSold, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalItemsSold, value); }
		}

		/// <summary>The TotalRevenue property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_revenue".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalRevenue
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.TotalRevenue, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalRevenue, value); }
		}

		/// <summary>The TotalShipping property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_shipping".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalShipping
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.TotalShipping, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalShipping, value); }
		}

		/// <summary>The TotalSubtotal property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_subtotal".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalSubtotal
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.TotalSubtotal, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalSubtotal, value); }
		}

		/// <summary>The TotalTax property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."total_tax".<br/>View field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalTax
		{
			get { return (System.Decimal)GetValue((int)SalesPerformanceViewFieldIndex.TotalTax, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.TotalTax, value); }
		}

		/// <summary>The UniqueCustomers property of the Entity SalesPerformanceView<br/><br/></summary>
		/// <remarks>Mapped on  view field: "sales_performance_view"."unique_customers".<br/>View field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>View field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 UniqueCustomers
		{
			get { return (System.Int64)GetValue((int)SalesPerformanceViewFieldIndex.UniqueCustomers, true); }
			set { SetValue((int)SalesPerformanceViewFieldIndex.UniqueCustomers, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum SalesPerformanceViewFieldIndex
	{
		///<summary>AverageOrderValue. </summary>
		AverageOrderValue,
		///<summary>OrdersCount. </summary>
		OrdersCount,
		///<summary>SaleDate. </summary>
		SaleDate,
		///<summary>TotalDiscounts. </summary>
		TotalDiscounts,
		///<summary>TotalItemsSold. </summary>
		TotalItemsSold,
		///<summary>TotalRevenue. </summary>
		TotalRevenue,
		///<summary>TotalShipping. </summary>
		TotalShipping,
		///<summary>TotalSubtotal. </summary>
		TotalSubtotal,
		///<summary>TotalTax. </summary>
		TotalTax,
		///<summary>UniqueCustomers. </summary>
		UniqueCustomers,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SalesPerformanceView. </summary>
	public partial class SalesPerformanceViewRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSalesPerformanceViewRelations
	{

		/// <summary>CTor</summary>
		static StaticSalesPerformanceViewRelations() { }
	}
}
