//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ecommerce.HelperClasses;
using ecommerce.FactoryClasses;
using ecommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ecommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'User'.<br/><br/></summary>
	[Serializable]
	public partial class UserEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<AddressEntity> _addresses;
		private EntityCollection<CartEntity> _carts;
		private EntityCollection<CouponUsageEntity> _couponUsages;
		private EntityCollection<OrderEntity> _orders;
		private EntityCollection<PaymentEntity> _payments;
		private EntityCollection<ReviewEntity> _reviews;
		private EntityCollection<SavedPaymentMethodEntity> _savedPaymentMethods;
		private EntityCollection<WishlistEntity> _wishlists;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UserEntityStaticMetaData _staticMetaData = new UserEntityStaticMetaData();
		private static UserRelations _relationsFactory = new UserRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Addresses</summary>
			public static readonly string Addresses = "Addresses";
			/// <summary>Member name Carts</summary>
			public static readonly string Carts = "Carts";
			/// <summary>Member name CouponUsages</summary>
			public static readonly string CouponUsages = "CouponUsages";
			/// <summary>Member name Orders</summary>
			public static readonly string Orders = "Orders";
			/// <summary>Member name Payments</summary>
			public static readonly string Payments = "Payments";
			/// <summary>Member name Reviews</summary>
			public static readonly string Reviews = "Reviews";
			/// <summary>Member name SavedPaymentMethods</summary>
			public static readonly string SavedPaymentMethods = "SavedPaymentMethods";
			/// <summary>Member name Wishlists</summary>
			public static readonly string Wishlists = "Wishlists";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserEntity", InheritanceHierarchyType.None, false, (int)ecommerce.EntityType.UserEntity, typeof(UserEntity), typeof(UserEntityFactory), false);
				AddNavigatorMetaData<UserEntity, EntityCollection<AddressEntity>>("Addresses", a => a._addresses, (a, b) => a._addresses = b, a => a.Addresses, () => new UserRelations().AddressEntityUsingUserId, typeof(AddressEntity), (int)ecommerce.EntityType.AddressEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<CartEntity>>("Carts", a => a._carts, (a, b) => a._carts = b, a => a.Carts, () => new UserRelations().CartEntityUsingUserId, typeof(CartEntity), (int)ecommerce.EntityType.CartEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<CouponUsageEntity>>("CouponUsages", a => a._couponUsages, (a, b) => a._couponUsages = b, a => a.CouponUsages, () => new UserRelations().CouponUsageEntityUsingUserId, typeof(CouponUsageEntity), (int)ecommerce.EntityType.CouponUsageEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<OrderEntity>>("Orders", a => a._orders, (a, b) => a._orders = b, a => a.Orders, () => new UserRelations().OrderEntityUsingUserId, typeof(OrderEntity), (int)ecommerce.EntityType.OrderEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<PaymentEntity>>("Payments", a => a._payments, (a, b) => a._payments = b, a => a.Payments, () => new UserRelations().PaymentEntityUsingUserId, typeof(PaymentEntity), (int)ecommerce.EntityType.PaymentEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<ReviewEntity>>("Reviews", a => a._reviews, (a, b) => a._reviews = b, a => a.Reviews, () => new UserRelations().ReviewEntityUsingUserId, typeof(ReviewEntity), (int)ecommerce.EntityType.ReviewEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<SavedPaymentMethodEntity>>("SavedPaymentMethods", a => a._savedPaymentMethods, (a, b) => a._savedPaymentMethods = b, a => a.SavedPaymentMethods, () => new UserRelations().SavedPaymentMethodEntityUsingUserId, typeof(SavedPaymentMethodEntity), (int)ecommerce.EntityType.SavedPaymentMethodEntity);
				AddNavigatorMetaData<UserEntity, EntityCollection<WishlistEntity>>("Wishlists", a => a._wishlists, (a, b) => a._wishlists = b, a => a.Wishlists, () => new UserRelations().WishlistEntityUsingUserId, typeof(WishlistEntity), (int)ecommerce.EntityType.WishlistEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserEntity</param>
		public UserEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for User which data should be fetched into this User object</param>
		public UserEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for User which data should be fetched into this User object</param>
		/// <param name="validator">The custom validator object for this UserEntity</param>
		public UserEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Address' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAddresses() { return CreateRelationInfoForNavigator("Addresses"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Cart' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCarts() { return CreateRelationInfoForNavigator("Carts"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CouponUsage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCouponUsages() { return CreateRelationInfoForNavigator("CouponUsages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrders() { return CreateRelationInfoForNavigator("Orders"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Payment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPayments() { return CreateRelationInfoForNavigator("Payments"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Review' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReviews() { return CreateRelationInfoForNavigator("Reviews"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'SavedPaymentMethod' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSavedPaymentMethods() { return CreateRelationInfoForNavigator("SavedPaymentMethods"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Wishlist' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWishlists() { return CreateRelationInfoForNavigator("Wishlists"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Address' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAddresses { get { return _staticMetaData.GetPrefetchPathElement("Addresses", CommonEntityBase.CreateEntityCollection<AddressEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Cart' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCarts { get { return _staticMetaData.GetPrefetchPathElement("Carts", CommonEntityBase.CreateEntityCollection<CartEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CouponUsage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCouponUsages { get { return _staticMetaData.GetPrefetchPathElement("CouponUsages", CommonEntityBase.CreateEntityCollection<CouponUsageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrders { get { return _staticMetaData.GetPrefetchPathElement("Orders", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Payment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPayments { get { return _staticMetaData.GetPrefetchPathElement("Payments", CommonEntityBase.CreateEntityCollection<PaymentEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Review' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReviews { get { return _staticMetaData.GetPrefetchPathElement("Reviews", CommonEntityBase.CreateEntityCollection<ReviewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SavedPaymentMethod' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSavedPaymentMethods { get { return _staticMetaData.GetPrefetchPathElement("SavedPaymentMethods", CommonEntityBase.CreateEntityCollection<SavedPaymentMethodEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Wishlist' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWishlists { get { return _staticMetaData.GetPrefetchPathElement("Wishlists", CommonEntityBase.CreateEntityCollection<WishlistEntity>()); } }

		/// <summary>The CreatedAt property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)UserFieldIndex.CreatedAt, true); }
			set { SetValue((int)UserFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Email property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)UserFieldIndex.Email, true); }
			set { SetValue((int)UserFieldIndex.Email, value); }
		}

		/// <summary>The EmailVerificationToken property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."email_verification_token".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String EmailVerificationToken
		{
			get { return (System.String)GetValue((int)UserFieldIndex.EmailVerificationToken, true); }
			set { SetValue((int)UserFieldIndex.EmailVerificationToken, value); }
		}

		/// <summary>The FailedLoginAttempts property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."failed_login_attempts".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 FailedLoginAttempts
		{
			get { return (System.Int32)GetValue((int)UserFieldIndex.FailedLoginAttempts, true); }
			set { SetValue((int)UserFieldIndex.FailedLoginAttempts, value); }
		}

		/// <summary>The FirstName property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."first_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String FirstName
		{
			get { return (System.String)GetValue((int)UserFieldIndex.FirstName, true); }
			set { SetValue((int)UserFieldIndex.FirstName, value); }
		}

		/// <summary>The Id property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)UserFieldIndex.Id, true); }
			set { SetValue((int)UserFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)UserFieldIndex.IsActive, true); }
			set { SetValue((int)UserFieldIndex.IsActive, value); }
		}

		/// <summary>The IsEmailVerified property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."is_email_verified".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsEmailVerified
		{
			get { return (System.Boolean)GetValue((int)UserFieldIndex.IsEmailVerified, true); }
			set { SetValue((int)UserFieldIndex.IsEmailVerified, value); }
		}

		/// <summary>The LastLoginAt property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."last_login_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LastLoginAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserFieldIndex.LastLoginAt, false); }
			set { SetValue((int)UserFieldIndex.LastLoginAt, value); }
		}

		/// <summary>The LastName property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."last_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String LastName
		{
			get { return (System.String)GetValue((int)UserFieldIndex.LastName, true); }
			set { SetValue((int)UserFieldIndex.LastName, value); }
		}

		/// <summary>The LockoutEnd property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."lockout_end".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LockoutEnd
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserFieldIndex.LockoutEnd, false); }
			set { SetValue((int)UserFieldIndex.LockoutEnd, value); }
		}

		/// <summary>The PasswordHash property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."password_hash".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String PasswordHash
		{
			get { return (System.String)GetValue((int)UserFieldIndex.PasswordHash, true); }
			set { SetValue((int)UserFieldIndex.PasswordHash, value); }
		}

		/// <summary>The PasswordResetExpires property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."password_reset_expires".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> PasswordResetExpires
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserFieldIndex.PasswordResetExpires, false); }
			set { SetValue((int)UserFieldIndex.PasswordResetExpires, value); }
		}

		/// <summary>The PasswordResetToken property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."password_reset_token".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PasswordResetToken
		{
			get { return (System.String)GetValue((int)UserFieldIndex.PasswordResetToken, true); }
			set { SetValue((int)UserFieldIndex.PasswordResetToken, value); }
		}

		/// <summary>The PhoneNumber property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."phone_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PhoneNumber
		{
			get { return (System.String)GetValue((int)UserFieldIndex.PhoneNumber, true); }
			set { SetValue((int)UserFieldIndex.PhoneNumber, value); }
		}

		/// <summary>The Role property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."role".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Role
		{
			get { return (System.String)GetValue((int)UserFieldIndex.Role, true); }
			set { SetValue((int)UserFieldIndex.Role, value); }
		}

		/// <summary>The UpdatedAt property of the Entity User<br/><br/></summary>
		/// <remarks>Mapped on  table field: "users"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UpdatedAt
		{
			get { return (System.DateTime)GetValue((int)UserFieldIndex.UpdatedAt, true); }
			set { SetValue((int)UserFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AddressEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AddressEntity))]
		public virtual EntityCollection<AddressEntity> Addresses { get { return GetOrCreateEntityCollection<AddressEntity, AddressEntityFactory>("User", true, false, ref _addresses); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'CartEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CartEntity))]
		public virtual EntityCollection<CartEntity> Carts { get { return GetOrCreateEntityCollection<CartEntity, CartEntityFactory>("User", true, false, ref _carts); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'CouponUsageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CouponUsageEntity))]
		public virtual EntityCollection<CouponUsageEntity> CouponUsages { get { return GetOrCreateEntityCollection<CouponUsageEntity, CouponUsageEntityFactory>("User", true, false, ref _couponUsages); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderEntity))]
		public virtual EntityCollection<OrderEntity> Orders { get { return GetOrCreateEntityCollection<OrderEntity, OrderEntityFactory>("User", true, false, ref _orders); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'PaymentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PaymentEntity))]
		public virtual EntityCollection<PaymentEntity> Payments { get { return GetOrCreateEntityCollection<PaymentEntity, PaymentEntityFactory>("User", true, false, ref _payments); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ReviewEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ReviewEntity))]
		public virtual EntityCollection<ReviewEntity> Reviews { get { return GetOrCreateEntityCollection<ReviewEntity, ReviewEntityFactory>("User", true, false, ref _reviews); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'SavedPaymentMethodEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(SavedPaymentMethodEntity))]
		public virtual EntityCollection<SavedPaymentMethodEntity> SavedPaymentMethods { get { return GetOrCreateEntityCollection<SavedPaymentMethodEntity, SavedPaymentMethodEntityFactory>("User", true, false, ref _savedPaymentMethods); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WishlistEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WishlistEntity))]
		public virtual EntityCollection<WishlistEntity> Wishlists { get { return GetOrCreateEntityCollection<WishlistEntity, WishlistEntityFactory>("User", true, false, ref _wishlists); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ecommerce
{
	public enum UserFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Email. </summary>
		Email,
		///<summary>EmailVerificationToken. </summary>
		EmailVerificationToken,
		///<summary>FailedLoginAttempts. </summary>
		FailedLoginAttempts,
		///<summary>FirstName. </summary>
		FirstName,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>IsEmailVerified. </summary>
		IsEmailVerified,
		///<summary>LastLoginAt. </summary>
		LastLoginAt,
		///<summary>LastName. </summary>
		LastName,
		///<summary>LockoutEnd. </summary>
		LockoutEnd,
		///<summary>PasswordHash. </summary>
		PasswordHash,
		///<summary>PasswordResetExpires. </summary>
		PasswordResetExpires,
		///<summary>PasswordResetToken. </summary>
		PasswordResetToken,
		///<summary>PhoneNumber. </summary>
		PhoneNumber,
		///<summary>Role. </summary>
		Role,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ecommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: User. </summary>
	public partial class UserRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between UserEntity and AddressEntity over the 1:n relation they have, using the relation between the fields: User.Id - Address.UserId</summary>
		public virtual IEntityRelation AddressEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Addresses", true, new[] { UserFields.Id, AddressFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and CartEntity over the 1:n relation they have, using the relation between the fields: User.Id - Cart.UserId</summary>
		public virtual IEntityRelation CartEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Carts", true, new[] { UserFields.Id, CartFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and CouponUsageEntity over the 1:n relation they have, using the relation between the fields: User.Id - CouponUsage.UserId</summary>
		public virtual IEntityRelation CouponUsageEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CouponUsages", true, new[] { UserFields.Id, CouponUsageFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and OrderEntity over the 1:n relation they have, using the relation between the fields: User.Id - Order.UserId</summary>
		public virtual IEntityRelation OrderEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Orders", true, new[] { UserFields.Id, OrderFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and PaymentEntity over the 1:n relation they have, using the relation between the fields: User.Id - Payment.UserId</summary>
		public virtual IEntityRelation PaymentEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Payments", true, new[] { UserFields.Id, PaymentFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and ReviewEntity over the 1:n relation they have, using the relation between the fields: User.Id - Review.UserId</summary>
		public virtual IEntityRelation ReviewEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Reviews", true, new[] { UserFields.Id, ReviewFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and SavedPaymentMethodEntity over the 1:n relation they have, using the relation between the fields: User.Id - SavedPaymentMethod.UserId</summary>
		public virtual IEntityRelation SavedPaymentMethodEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "SavedPaymentMethods", true, new[] { UserFields.Id, SavedPaymentMethodFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserEntity and WishlistEntity over the 1:n relation they have, using the relation between the fields: User.Id - Wishlist.UserId</summary>
		public virtual IEntityRelation WishlistEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Wishlists", true, new[] { UserFields.Id, WishlistFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserRelations
	{
		internal static readonly IEntityRelation AddressEntityUsingUserIdStatic = new UserRelations().AddressEntityUsingUserId;
		internal static readonly IEntityRelation CartEntityUsingUserIdStatic = new UserRelations().CartEntityUsingUserId;
		internal static readonly IEntityRelation CouponUsageEntityUsingUserIdStatic = new UserRelations().CouponUsageEntityUsingUserId;
		internal static readonly IEntityRelation OrderEntityUsingUserIdStatic = new UserRelations().OrderEntityUsingUserId;
		internal static readonly IEntityRelation PaymentEntityUsingUserIdStatic = new UserRelations().PaymentEntityUsingUserId;
		internal static readonly IEntityRelation ReviewEntityUsingUserIdStatic = new UserRelations().ReviewEntityUsingUserId;
		internal static readonly IEntityRelation SavedPaymentMethodEntityUsingUserIdStatic = new UserRelations().SavedPaymentMethodEntityUsingUserId;
		internal static readonly IEntityRelation WishlistEntityUsingUserIdStatic = new UserRelations().WishlistEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticUserRelations() { }
	}
}
