//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Address'.</summary>
	[Serializable]
	[DataContract]
	public partial class AddressView
	{
		/// <summary>Gets or sets the AddressLine1 field. Derived from Entity Model Field 'Address.AddressLine1'</summary>
		[DataMember]
		public System.String AddressLine1 { get; set; }
		/// <summary>Gets or sets the AddressLine2 field. Derived from Entity Model Field 'Address.AddressLine2'</summary>
		[DataMember]
		public System.String AddressLine2 { get; set; }
		/// <summary>Gets or sets the AddressType field. Derived from Entity Model Field 'Address.AddressType'</summary>
		[DataMember]
		public System.String AddressType { get; set; }
		/// <summary>Gets or sets the City field. Derived from Entity Model Field 'Address.City'</summary>
		[DataMember]
		public System.String City { get; set; }
		/// <summary>Gets or sets the Country field. Derived from Entity Model Field 'Address.Country'</summary>
		[DataMember]
		public System.String Country { get; set; }
		/// <summary>Gets or sets the CreatedAt field. Derived from Entity Model Field 'Address.CreatedAt'</summary>
		[DataMember]
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the FullName field. Derived from Entity Model Field 'Address.FullName'</summary>
		[DataMember]
		public System.String FullName { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Address.Id'</summary>
		[DataMember]
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the IsDefault field. Derived from Entity Model Field 'Address.IsDefault'</summary>
		[DataMember]
		public System.Boolean IsDefault { get; set; }
		/// <summary>Gets or sets the PhoneNumber field. Derived from Entity Model Field 'Address.PhoneNumber'</summary>
		[DataMember]
		public System.String PhoneNumber { get; set; }
		/// <summary>Gets or sets the PostalCode field. Derived from Entity Model Field 'Address.PostalCode'</summary>
		[DataMember]
		public System.String PostalCode { get; set; }
		/// <summary>Gets or sets the State field. Derived from Entity Model Field 'Address.State'</summary>
		[DataMember]
		public System.String State { get; set; }
		/// <summary>Gets or sets the UpdatedAt field. Derived from Entity Model Field 'Address.UpdatedAt'</summary>
		[DataMember]
		public System.DateTime UpdatedAt { get; set; }
		/// <summary>Gets or sets the UserId field. Derived from Entity Model Field 'Address.UserId (FK)'</summary>
		[DataMember]
		public System.Guid UserId { get; set; }
	}

}




