//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Linq;
using System.Collections.Generic;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using ECommerce.Data.EntityClasses;
using ECommerce.Data.FactoryClasses;

namespace ECommerce.Data.Linq
{
	/// <summary>Meta-data class for the construction of Linq queries which are to be executed using LLBLGen Pro code.</summary>
	public partial class LinqMetaData: ILinqMetaData
	{
		/// <summary>CTor. Using this ctor will leave the IDataAccessAdapter object to use empty. To be able to execute the query, an IDataAccessAdapter instance
		/// is required, and has to be set on the LLBLGenProProvider2 object in the query to execute. </summary>
		public LinqMetaData() : this(null, null) { }
		
		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse) : this (adapterToUse, null) { }

		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <param name="customFunctionMappings">The custom function mappings to use. These take higher precedence than the ones in the DQE to use.</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse, FunctionMappingStore customFunctionMappings)
		{
			this.AdapterToUse = adapterToUse;
			this.CustomFunctionMappings = customFunctionMappings;
		}
	
		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <param name="typeOfEntity">the type of the entity to get the datasource for</param>
		/// <returns>the requested datasource</returns>
		public IDataSource GetQueryableForEntity(int typeOfEntity)
		{
			switch((ECommerce.Data.EntityType)typeOfEntity)
			{
				case ECommerce.Data.EntityType.AddressEntity:
					return this.Address;
				case ECommerce.Data.EntityType.CartEntity:
					return this.Cart;
				case ECommerce.Data.EntityType.CartItemEntity:
					return this.CartItem;
				case ECommerce.Data.EntityType.CartSummaryViewEntity:
					return this.CartSummaryView;
				case ECommerce.Data.EntityType.CategoryEntity:
					return this.Category;
				case ECommerce.Data.EntityType.CategoryPerformanceViewEntity:
					return this.CategoryPerformanceView;
				case ECommerce.Data.EntityType.CouponEntity:
					return this.Coupon;
				case ECommerce.Data.EntityType.CouponUsageEntity:
					return this.CouponUsage;
				case ECommerce.Data.EntityType.CustomerOrdersViewEntity:
					return this.CustomerOrdersView;
				case ECommerce.Data.EntityType.OrderEntity:
					return this.Order;
				case ECommerce.Data.EntityType.OrderItemEntity:
					return this.OrderItem;
				case ECommerce.Data.EntityType.OrderSummaryViewEntity:
					return this.OrderSummaryView;
				case ECommerce.Data.EntityType.PaymentEntity:
					return this.Payment;
				case ECommerce.Data.EntityType.ProductEntity:
					return this.Product;
				case ECommerce.Data.EntityType.ProductImageEntity:
					return this.ProductImage;
				case ECommerce.Data.EntityType.ProductInventoryViewEntity:
					return this.ProductInventoryView;
				case ECommerce.Data.EntityType.ProductRatingViewEntity:
					return this.ProductRatingView;
				case ECommerce.Data.EntityType.ReviewEntity:
					return this.Review;
				case ECommerce.Data.EntityType.SalesPerformanceViewEntity:
					return this.SalesPerformanceView;
				case ECommerce.Data.EntityType.SavedPaymentMethodEntity:
					return this.SavedPaymentMethod;
				case ECommerce.Data.EntityType.UserEntity:
					return this.User;
				case ECommerce.Data.EntityType.WishlistEntity:
					return this.Wishlist;
				case ECommerce.Data.EntityType.WishlistItemEntity:
					return this.WishlistItem;
				default:
					return null;
			}
		}

		/// <summary>returns the datasource to use in a Linq query which wraps the specified SQL query and projects it to instances of type T</summary>
		/// <param name="sqlQuery">The SQL query to execute. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		/// <param name="parameterValues">The object which will provide the parameter values for the SQL query specified. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		/// <typeparam name="T">The type of the instances to project the rows into, returned by the SQL query specified</typeparam>
		/// <returns>the requested datasource</returns>
		[InMemoryCandidate]
		public DataSource2<T> FromSql<T>(string sqlQuery, object parameterValues)
			where T : class
		{
			return new DataSource2<T>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse).SetWrappedPlainSQLQuerySpecification(sqlQuery, parameterValues);
		}

		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <typeparam name="TEntity">the type of the entity to get the datasource for</typeparam>
		/// <returns>the requested datasource</returns>
		public DataSource2<TEntity> GetQueryableForEntity<TEntity>()
				where TEntity : class
		{
			return new DataSource2<TEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse);
		}

		/// <summary>returns the datasource to use in a Linq query when targeting AddressEntity instances in the database.</summary>
		public DataSource2<AddressEntity> Address {	get { return new DataSource2<AddressEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CartEntity instances in the database.</summary>
		public DataSource2<CartEntity> Cart {	get { return new DataSource2<CartEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CartItemEntity instances in the database.</summary>
		public DataSource2<CartItemEntity> CartItem {	get { return new DataSource2<CartItemEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CartSummaryViewEntity instances in the database.</summary>
		public DataSource2<CartSummaryViewEntity> CartSummaryView {	get { return new DataSource2<CartSummaryViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CategoryEntity instances in the database.</summary>
		public DataSource2<CategoryEntity> Category {	get { return new DataSource2<CategoryEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CategoryPerformanceViewEntity instances in the database.</summary>
		public DataSource2<CategoryPerformanceViewEntity> CategoryPerformanceView {	get { return new DataSource2<CategoryPerformanceViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CouponEntity instances in the database.</summary>
		public DataSource2<CouponEntity> Coupon {	get { return new DataSource2<CouponEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CouponUsageEntity instances in the database.</summary>
		public DataSource2<CouponUsageEntity> CouponUsage {	get { return new DataSource2<CouponUsageEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CustomerOrdersViewEntity instances in the database.</summary>
		public DataSource2<CustomerOrdersViewEntity> CustomerOrdersView {	get { return new DataSource2<CustomerOrdersViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting OrderEntity instances in the database.</summary>
		public DataSource2<OrderEntity> Order {	get { return new DataSource2<OrderEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting OrderItemEntity instances in the database.</summary>
		public DataSource2<OrderItemEntity> OrderItem {	get { return new DataSource2<OrderItemEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting OrderSummaryViewEntity instances in the database.</summary>
		public DataSource2<OrderSummaryViewEntity> OrderSummaryView {	get { return new DataSource2<OrderSummaryViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting PaymentEntity instances in the database.</summary>
		public DataSource2<PaymentEntity> Payment {	get { return new DataSource2<PaymentEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductEntity instances in the database.</summary>
		public DataSource2<ProductEntity> Product {	get { return new DataSource2<ProductEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductImageEntity instances in the database.</summary>
		public DataSource2<ProductImageEntity> ProductImage {	get { return new DataSource2<ProductImageEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductInventoryViewEntity instances in the database.</summary>
		public DataSource2<ProductInventoryViewEntity> ProductInventoryView {	get { return new DataSource2<ProductInventoryViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductRatingViewEntity instances in the database.</summary>
		public DataSource2<ProductRatingViewEntity> ProductRatingView {	get { return new DataSource2<ProductRatingViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ReviewEntity instances in the database.</summary>
		public DataSource2<ReviewEntity> Review {	get { return new DataSource2<ReviewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting SalesPerformanceViewEntity instances in the database.</summary>
		public DataSource2<SalesPerformanceViewEntity> SalesPerformanceView {	get { return new DataSource2<SalesPerformanceViewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting SavedPaymentMethodEntity instances in the database.</summary>
		public DataSource2<SavedPaymentMethodEntity> SavedPaymentMethod {	get { return new DataSource2<SavedPaymentMethodEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserEntity instances in the database.</summary>
		public DataSource2<UserEntity> User {	get { return new DataSource2<UserEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting WishlistEntity instances in the database.</summary>
		public DataSource2<WishlistEntity> Wishlist {	get { return new DataSource2<WishlistEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting WishlistItemEntity instances in the database.</summary>
		public DataSource2<WishlistItemEntity> WishlistItem {	get { return new DataSource2<WishlistItemEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		


		/// <summary> Gets / sets the IDataAccessAdapter to use for the queries created with this meta data object.</summary>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data
		/// till they go out of scope.</remarks>
		public IDataAccessAdapter AdapterToUse { get; set; }
		
		/// <summary>Gets or sets the custom function mappings to use. These take higher precedence than the ones in the DQE to use</summary>
		public FunctionMappingStore CustomFunctionMappings { get; set; }
		
		/// <summary>Gets or sets the Context instance to use for entity fetches.</summary>
		public Context ContextToUse { get; set; }
	}
}